/*
CMS Multi-Tenant System API

API documentation for the CMS Multi-Tenant System

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PageRequestGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PageRequestGet200Response{}

// PageRequestGet200Response struct for PageRequestGet200Response
type PageRequestGet200Response struct {
	Data []PageRequestResponse `json:"data,omitempty"`
	Pagination *Pagination `json:"pagination,omitempty"`
}

// NewPageRequestGet200Response instantiates a new PageRequestGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPageRequestGet200Response() *PageRequestGet200Response {
	this := PageRequestGet200Response{}
	return &this
}

// NewPageRequestGet200ResponseWithDefaults instantiates a new PageRequestGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPageRequestGet200ResponseWithDefaults() *PageRequestGet200Response {
	this := PageRequestGet200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *PageRequestGet200Response) GetData() []PageRequestResponse {
	if o == nil || IsNil(o.Data) {
		var ret []PageRequestResponse
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PageRequestGet200Response) GetDataOk() ([]PageRequestResponse, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *PageRequestGet200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []PageRequestResponse and assigns it to the Data field.
func (o *PageRequestGet200Response) SetData(v []PageRequestResponse) {
	o.Data = v
}

// GetPagination returns the Pagination field value if set, zero value otherwise.
func (o *PageRequestGet200Response) GetPagination() Pagination {
	if o == nil || IsNil(o.Pagination) {
		var ret Pagination
		return ret
	}
	return *o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PageRequestGet200Response) GetPaginationOk() (*Pagination, bool) {
	if o == nil || IsNil(o.Pagination) {
		return nil, false
	}
	return o.Pagination, true
}

// HasPagination returns a boolean if a field has been set.
func (o *PageRequestGet200Response) HasPagination() bool {
	if o != nil && !IsNil(o.Pagination) {
		return true
	}

	return false
}

// SetPagination gets a reference to the given Pagination and assigns it to the Pagination field.
func (o *PageRequestGet200Response) SetPagination(v Pagination) {
	o.Pagination = &v
}

func (o PageRequestGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PageRequestGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Pagination) {
		toSerialize["pagination"] = o.Pagination
	}
	return toSerialize, nil
}

type NullablePageRequestGet200Response struct {
	value *PageRequestGet200Response
	isSet bool
}

func (v NullablePageRequestGet200Response) Get() *PageRequestGet200Response {
	return v.value
}

func (v *NullablePageRequestGet200Response) Set(val *PageRequestGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullablePageRequestGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullablePageRequestGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePageRequestGet200Response(val *PageRequestGet200Response) *NullablePageRequestGet200Response {
	return &NullablePageRequestGet200Response{value: val, isSet: true}
}

func (v NullablePageRequestGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePageRequestGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


