// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: users/users.service.proto

/*
Package users is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package users

import (
	"context"
	"errors"
	"io"
	"net/http"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/v2/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
)

// Suppress "imported and not used" errors
var (
	_ codes.Code
	_ io.Reader
	_ status.Status
	_ = errors.New
	_ = runtime.String
	_ = utilities.NewDoubleArray
	_ = metadata.Join
)

func request_LMS_USER_SERVICE_CreateLMSUser_0(ctx context.Context, marshaler runtime.Marshaler, client LMS_USER_SERVICEClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq CreateLMSUserRequest
		metadata runtime.ServerMetadata
	)
	if err := marshaler.NewDecoder(req.Body).Decode(&protoReq); err != nil && !errors.Is(err, io.EOF) {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if req.Body != nil {
		_, _ = io.Copy(io.Discard, req.Body)
	}
	msg, err := client.CreateLMSUser(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err
}

func local_request_LMS_USER_SERVICE_CreateLMSUser_0(ctx context.Context, marshaler runtime.Marshaler, server LMS_USER_SERVICEServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq CreateLMSUserRequest
		metadata runtime.ServerMetadata
	)
	if err := marshaler.NewDecoder(req.Body).Decode(&protoReq); err != nil && !errors.Is(err, io.EOF) {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	msg, err := server.CreateLMSUser(ctx, &protoReq)
	return msg, metadata, err
}

// RegisterLMS_USER_SERVICEHandlerServer registers the http handlers for service LMS_USER_SERVICE to "mux".
// UnaryRPC     :call LMS_USER_SERVICEServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterLMS_USER_SERVICEHandlerFromEndpoint instead.
// GRPC interceptors will not work for this type of registration. To use interceptors, you must use the "runtime.WithMiddlewares" option in the "runtime.NewServeMux" call.
func RegisterLMS_USER_SERVICEHandlerServer(ctx context.Context, mux *runtime.ServeMux, server LMS_USER_SERVICEServer) error {
	mux.Handle(http.MethodPost, pattern_LMS_USER_SERVICE_CreateLMSUser_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateIncomingContext(ctx, mux, req, "/lms.users.LMS_USER_SERVICE/CreateLMSUser", runtime.WithHTTPPathPattern("/lms/v1/users"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_LMS_USER_SERVICE_CreateLMSUser_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_LMS_USER_SERVICE_CreateLMSUser_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})

	return nil
}

// RegisterLMS_USER_SERVICEHandlerFromEndpoint is same as RegisterLMS_USER_SERVICEHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterLMS_USER_SERVICEHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.NewClient(endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Errorf("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Errorf("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()
	return RegisterLMS_USER_SERVICEHandler(ctx, mux, conn)
}

// RegisterLMS_USER_SERVICEHandler registers the http handlers for service LMS_USER_SERVICE to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterLMS_USER_SERVICEHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterLMS_USER_SERVICEHandlerClient(ctx, mux, NewLMS_USER_SERVICEClient(conn))
}

// RegisterLMS_USER_SERVICEHandlerClient registers the http handlers for service LMS_USER_SERVICE
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "LMS_USER_SERVICEClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "LMS_USER_SERVICEClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "LMS_USER_SERVICEClient" to call the correct interceptors. This client ignores the HTTP middlewares.
func RegisterLMS_USER_SERVICEHandlerClient(ctx context.Context, mux *runtime.ServeMux, client LMS_USER_SERVICEClient) error {
	mux.Handle(http.MethodPost, pattern_LMS_USER_SERVICE_CreateLMSUser_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateContext(ctx, mux, req, "/lms.users.LMS_USER_SERVICE/CreateLMSUser", runtime.WithHTTPPathPattern("/lms/v1/users"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_LMS_USER_SERVICE_CreateLMSUser_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_LMS_USER_SERVICE_CreateLMSUser_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})
	return nil
}

var (
	pattern_LMS_USER_SERVICE_CreateLMSUser_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2}, []string{"lms", "v1", "users"}, ""))
)

var (
	forward_LMS_USER_SERVICE_CreateLMSUser_0 = runtime.ForwardResponseMessage
)
