// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: users/users.service.proto

package users

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LMS_USER_SERVICE_CreateLMSUser_FullMethodName = "/lms.users.LMS_USER_SERVICE/CreateLMSUser"
)

// LMS_USER_SERVICEClient is the client API for LMS_USER_SERVICE service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LMS_USER_SERVICEClient interface {
	CreateLMSUser(ctx context.Context, in *CreateLMSUserRequest, opts ...grpc.CallOption) (*CreateLMSUserResponse, error)
}

type lMS_USER_SERVICEClient struct {
	cc grpc.ClientConnInterface
}

func NewLMS_USER_SERVICEClient(cc grpc.ClientConnInterface) LMS_USER_SERVICEClient {
	return &lMS_USER_SERVICEClient{cc}
}

func (c *lMS_USER_SERVICEClient) CreateLMSUser(ctx context.Context, in *CreateLMSUserRequest, opts ...grpc.CallOption) (*CreateLMSUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateLMSUserResponse)
	err := c.cc.Invoke(ctx, LMS_USER_SERVICE_CreateLMSUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LMS_USER_SERVICEServer is the server API for LMS_USER_SERVICE service.
// All implementations must embed UnimplementedLMS_USER_SERVICEServer
// for forward compatibility.
type LMS_USER_SERVICEServer interface {
	CreateLMSUser(context.Context, *CreateLMSUserRequest) (*CreateLMSUserResponse, error)
	mustEmbedUnimplementedLMS_USER_SERVICEServer()
}

// UnimplementedLMS_USER_SERVICEServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLMS_USER_SERVICEServer struct{}

func (UnimplementedLMS_USER_SERVICEServer) CreateLMSUser(context.Context, *CreateLMSUserRequest) (*CreateLMSUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLMSUser not implemented")
}
func (UnimplementedLMS_USER_SERVICEServer) mustEmbedUnimplementedLMS_USER_SERVICEServer() {}
func (UnimplementedLMS_USER_SERVICEServer) testEmbeddedByValue()                          {}

// UnsafeLMS_USER_SERVICEServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LMS_USER_SERVICEServer will
// result in compilation errors.
type UnsafeLMS_USER_SERVICEServer interface {
	mustEmbedUnimplementedLMS_USER_SERVICEServer()
}

func RegisterLMS_USER_SERVICEServer(s grpc.ServiceRegistrar, srv LMS_USER_SERVICEServer) {
	// If the following call pancis, it indicates UnimplementedLMS_USER_SERVICEServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LMS_USER_SERVICE_ServiceDesc, srv)
}

func _LMS_USER_SERVICE_CreateLMSUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLMSUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LMS_USER_SERVICEServer).CreateLMSUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LMS_USER_SERVICE_CreateLMSUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LMS_USER_SERVICEServer).CreateLMSUser(ctx, req.(*CreateLMSUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LMS_USER_SERVICE_ServiceDesc is the grpc.ServiceDesc for LMS_USER_SERVICE service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LMS_USER_SERVICE_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lms.users.LMS_USER_SERVICE",
	HandlerType: (*LMS_USER_SERVICEServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLMSUser",
			Handler:    _LMS_USER_SERVICE_CreateLMSUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "users/users.service.proto",
}
