// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type CourseStatus string

const (
	CourseStatusPending     CourseStatus = "Pending"
	CourseStatusPublished   CourseStatus = "Published"
	CourseStatusUnpublished CourseStatus = "Unpublished"
	CourseStatusArchived    CourseStatus = "Archived"
)

func (e *CourseStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CourseStatus(s)
	case string:
		*e = CourseStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CourseStatus: %T", src)
	}
	return nil
}

type NullCourseStatus struct {
	CourseStatus CourseStatus `json:"course_status"`
	Valid        bool         `json:"valid"` // Valid is true if CourseStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCourseStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CourseStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CourseStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCourseStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CourseStatus), nil
}

type EnrollmentType string

const (
	EnrollmentTypeENROLLED  EnrollmentType = "ENROLLED"
	EnrollmentTypeCOMPLETED EnrollmentType = "COMPLETED"
	EnrollmentTypeDROPPED   EnrollmentType = "DROPPED"
)

func (e *EnrollmentType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EnrollmentType(s)
	case string:
		*e = EnrollmentType(s)
	default:
		return fmt.Errorf("unsupported scan type for EnrollmentType: %T", src)
	}
	return nil
}

type NullEnrollmentType struct {
	EnrollmentType EnrollmentType `json:"enrollment_type"`
	Valid          bool           `json:"valid"` // Valid is true if EnrollmentType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEnrollmentType) Scan(value interface{}) error {
	if value == nil {
		ns.EnrollmentType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EnrollmentType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEnrollmentType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EnrollmentType), nil
}

type LmsRoleType string

const (
	LmsRoleTypeLMSADMIN   LmsRoleType = "LMS_ADMIN"
	LmsRoleTypeSTUDENT    LmsRoleType = "STUDENT"
	LmsRoleTypeINSTRUCTOR LmsRoleType = "INSTRUCTOR"
)

func (e *LmsRoleType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LmsRoleType(s)
	case string:
		*e = LmsRoleType(s)
	default:
		return fmt.Errorf("unsupported scan type for LmsRoleType: %T", src)
	}
	return nil
}

type NullLmsRoleType struct {
	LmsRoleType LmsRoleType `json:"lms_role_type"`
	Valid       bool        `json:"valid"` // Valid is true if LmsRoleType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLmsRoleType) Scan(value interface{}) error {
	if value == nil {
		ns.LmsRoleType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LmsRoleType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLmsRoleType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LmsRoleType), nil
}

type MaterialType string

const (
	MaterialTypeVideo MaterialType = "Video"
	MaterialTypePDF   MaterialType = "PDF"
	MaterialTypeSlide MaterialType = "Slide"
	MaterialTypeLink  MaterialType = "Link"
)

func (e *MaterialType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MaterialType(s)
	case string:
		*e = MaterialType(s)
	default:
		return fmt.Errorf("unsupported scan type for MaterialType: %T", src)
	}
	return nil
}

type NullMaterialType struct {
	MaterialType MaterialType `json:"material_type"`
	Valid        bool         `json:"valid"` // Valid is true if MaterialType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMaterialType) Scan(value interface{}) error {
	if value == nil {
		ns.MaterialType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MaterialType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMaterialType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MaterialType), nil
}

type SystemType string

const (
	SystemTypeLMS SystemType = "LMS"
	SystemTypeEMS SystemType = "EMS"
)

func (e *SystemType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SystemType(s)
	case string:
		*e = SystemType(s)
	default:
		return fmt.Errorf("unsupported scan type for SystemType: %T", src)
	}
	return nil
}

type NullSystemType struct {
	SystemType SystemType `json:"system_type"`
	Valid      bool       `json:"valid"` // Valid is true if SystemType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSystemType) Scan(value interface{}) error {
	if value == nil {
		ns.SystemType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SystemType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSystemType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SystemType), nil
}

type Assignment struct {
	AssignmentID pgtype.UUID      `json:"assignment_id"`
	CourseID     pgtype.UUID      `json:"course_id"`
	Title        string           `json:"title"`
	Instructions pgtype.Text      `json:"instructions"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

type Certificate struct {
	CertificateID  pgtype.UUID      `json:"certificate_id"`
	EnrollmentID   pgtype.UUID      `json:"enrollment_id"`
	IssueDate      pgtype.Timestamp `json:"issue_date"`
	CertificateUrl pgtype.Text      `json:"certificate_url"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

type Course struct {
	CourseID         pgtype.UUID      `json:"course_id"`
	CourseTitle      string           `json:"course_title"`
	Description      pgtype.Text      `json:"description"`
	InstructorID     pgtype.UUID      `json:"instructor_id"`
	OverallRating    pgtype.Int4      `json:"overall_rating"`
	CourseCategory   pgtype.UUID      `json:"course_category"`
	Status           NullCourseStatus `json:"status"`
	DurationDayCount pgtype.Int4      `json:"duration_day_count"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
	OwnedBy          pgtype.UUID      `json:"owned_by"`
}

type CourseCategory struct {
	CategoryID   pgtype.UUID      `json:"category_id"`
	CategoryName string           `json:"category_name"`
	Description  pgtype.Text      `json:"description"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

type Enrollment struct {
	EnrollmentID   pgtype.UUID      `json:"enrollment_id"`
	StudentID      pgtype.UUID      `json:"student_id"`
	CourseID       pgtype.UUID      `json:"course_id"`
	EnrollmentDate pgtype.Timestamp `json:"enrollment_date"`
	Progress       pgtype.Numeric   `json:"progress"`
	Status         EnrollmentType   `json:"status"`
	DueDate        pgtype.Timestamp `json:"due_date"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

type Lesson struct {
	LessonID     pgtype.UUID      `json:"lesson_id"`
	Title        string           `json:"title"`
	Content      pgtype.Text      `json:"content"`
	MaterialType NullMaterialType `json:"material_type"`
	ModuleID     pgtype.UUID      `json:"module_id"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

type LmsUser struct {
	LmsUserID        pgtype.UUID      `json:"lms_user_id"`
	LmsUserEmail     string           `json:"lms_user_email"`
	Password         string           `json:"password"`
	LmsRoleID        pgtype.UUID      `json:"lms_role_id"`
	TenantID         pgtype.UUID      `json:"tenant_id"`
	Address          pgtype.Text      `json:"address"`
	PhoneNumber      pgtype.Text      `json:"phone_number"`
	RegistrationDate pgtype.Date      `json:"registration_date"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
}

type LmsUserRole struct {
	LmsRoleID   pgtype.UUID `json:"lms_role_id"`
	LmsRoleName LmsRoleType `json:"lms_role_name"`
}

type Module struct {
	ModuleID    pgtype.UUID      `json:"module_id"`
	ModuleName  string           `json:"module_name"`
	CourseID    pgtype.UUID      `json:"course_id"`
	Description pgtype.Text      `json:"description"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type NamespaceConsumer struct {
	ConsumerID pgtype.UUID      `json:"consumer_id"`
	LmsUserID  pgtype.UUID      `json:"lms_user_id"`
	Namespace  string           `json:"namespace"`
	JoinedDate pgtype.Timestamp `json:"joined_date"`
	IsActive   pgtype.Bool      `json:"is_active"`
}

type Quiz struct {
	QuizID    pgtype.UUID      `json:"quiz_id"`
	Question  string           `json:"question"`
	Answer    string           `json:"answer"`
	ModuleID  pgtype.UUID      `json:"module_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type Rating struct {
	RatingID    pgtype.UUID      `json:"rating_id"`
	UserID      pgtype.UUID      `json:"user_id"`
	CourseID    pgtype.UUID      `json:"course_id"`
	RatingCount pgtype.Int4      `json:"rating_count"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type Report struct {
	ReportID          pgtype.UUID      `json:"report_id"`
	ReportName        string           `json:"report_name"`
	GeneratedByUserID pgtype.UUID      `json:"generated_by_user_id"`
	GeneratedDate     pgtype.Timestamp `json:"generated_date"`
	DataSnapshot      pgtype.Text      `json:"data_snapshot"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
}

type Review struct {
	ReviewID    pgtype.UUID      `json:"review_id"`
	CourseID    pgtype.UUID      `json:"course_id"`
	UserID      pgtype.UUID      `json:"user_id"`
	Title       pgtype.Text      `json:"title"`
	Description pgtype.Text      `json:"description"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type StudentQuiz struct {
	StudentQuizID pgtype.UUID      `json:"student_quiz_id"`
	StudentID     pgtype.UUID      `json:"student_id"`
	QuizID        pgtype.UUID      `json:"quiz_id"`
	Score         pgtype.Int4      `json:"score"`
	Attempt       pgtype.Int4      `json:"attempt"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

type Submission struct {
	SubmissionID pgtype.UUID      `json:"submission_id"`
	AssignmentID pgtype.UUID      `json:"assignment_id"`
	StudentID    pgtype.UUID      `json:"student_id"`
	SubmittedAt  pgtype.Timestamp `json:"submitted_at"`
	FileUrl      pgtype.Text      `json:"file_url"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

type Tenant struct {
	TenantID   pgtype.UUID      `json:"tenant_id"`
	Namespace  string           `json:"namespace"`
	CmsOwnerID pgtype.UUID      `json:"cms_owner_id"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	IsActive   pgtype.Bool      `json:"is_active"`
}

type TenantsMember struct {
	TmID       pgtype.UUID      `json:"tm_id"`
	LmsUserID  pgtype.UUID      `json:"lms_user_id"`
	TenantID   pgtype.UUID      `json:"tenant_id"`
	JoinedDate pgtype.Timestamp `json:"joined_date"`
	IsActive   pgtype.Bool      `json:"is_active"`
}
