// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: lesson/lesson.proto

package lesson

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Lesson struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	MaterialType  string                 `protobuf:"bytes,4,opt,name=material_type,json=materialType,proto3" json:"material_type,omitempty"`
	Module        *Module                `protobuf:"bytes,5,opt,name=module,proto3" json:"module,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lesson) Reset() {
	*x = Lesson{}
	mi := &file_lesson_lesson_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lesson) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lesson) ProtoMessage() {}

func (x *Lesson) ProtoReflect() protoreflect.Message {
	mi := &file_lesson_lesson_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lesson.ProtoReflect.Descriptor instead.
func (*Lesson) Descriptor() ([]byte, []int) {
	return file_lesson_lesson_proto_rawDescGZIP(), []int{0}
}

func (x *Lesson) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Lesson) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Lesson) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Lesson) GetMaterialType() string {
	if x != nil {
		return x.MaterialType
	}
	return ""
}

func (x *Lesson) GetModule() *Module {
	if x != nil {
		return x.Module
	}
	return nil
}

func (x *Lesson) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Lesson) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Module struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Module) Reset() {
	*x = Module{}
	mi := &file_lesson_lesson_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Module) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Module) ProtoMessage() {}

func (x *Module) ProtoReflect() protoreflect.Message {
	mi := &file_lesson_lesson_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Module.ProtoReflect.Descriptor instead.
func (*Module) Descriptor() ([]byte, []int) {
	return file_lesson_lesson_proto_rawDescGZIP(), []int{1}
}

func (x *Module) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Module) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_lesson_lesson_proto protoreflect.FileDescriptor

const file_lesson_lesson_proto_rawDesc = "" +
	"\n" +
	"\x13lesson/lesson.proto\x12\n" +
	"lms.lesson\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8f\x02\n" +
	"\x06Lesson\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12#\n" +
	"\rmaterial_type\x18\x04 \x01(\tR\fmaterialType\x12*\n" +
	"\x06module\x18\x05 \x01(\v2\x12.lms.lesson.ModuleR\x06module\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\",\n" +
	"\x06Module\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04nameB<Z:github.com/multi-tenant-cms-golang/lms-sys/protogen/lessonb\x06proto3"

var (
	file_lesson_lesson_proto_rawDescOnce sync.Once
	file_lesson_lesson_proto_rawDescData []byte
)

func file_lesson_lesson_proto_rawDescGZIP() []byte {
	file_lesson_lesson_proto_rawDescOnce.Do(func() {
		file_lesson_lesson_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lesson_lesson_proto_rawDesc), len(file_lesson_lesson_proto_rawDesc)))
	})
	return file_lesson_lesson_proto_rawDescData
}

var file_lesson_lesson_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_lesson_lesson_proto_goTypes = []any{
	(*Lesson)(nil),                // 0: lms.lesson.Lesson
	(*Module)(nil),                // 1: lms.lesson.Module
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_lesson_lesson_proto_depIdxs = []int32{
	1, // 0: lms.lesson.Lesson.module:type_name -> lms.lesson.Module
	2, // 1: lms.lesson.Lesson.created_at:type_name -> google.protobuf.Timestamp
	2, // 2: lms.lesson.Lesson.updated_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_lesson_lesson_proto_init() }
func file_lesson_lesson_proto_init() {
	if File_lesson_lesson_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lesson_lesson_proto_rawDesc), len(file_lesson_lesson_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lesson_lesson_proto_goTypes,
		DependencyIndexes: file_lesson_lesson_proto_depIdxs,
		MessageInfos:      file_lesson_lesson_proto_msgTypes,
	}.Build()
	File_lesson_lesson_proto = out.File
	file_lesson_lesson_proto_goTypes = nil
	file_lesson_lesson_proto_depIdxs = nil
}
