// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: lesson/rpc_lesson_get.proto

package lesson

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetLessonsByModuleIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModuleId      string                 `protobuf:"bytes,1,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLessonsByModuleIdRequest) Reset() {
	*x = GetLessonsByModuleIdRequest{}
	mi := &file_lesson_rpc_lesson_get_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLessonsByModuleIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLessonsByModuleIdRequest) ProtoMessage() {}

func (x *GetLessonsByModuleIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lesson_rpc_lesson_get_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLessonsByModuleIdRequest.ProtoReflect.Descriptor instead.
func (*GetLessonsByModuleIdRequest) Descriptor() ([]byte, []int) {
	return file_lesson_rpc_lesson_get_proto_rawDescGZIP(), []int{0}
}

func (x *GetLessonsByModuleIdRequest) GetModuleId() string {
	if x != nil {
		return x.ModuleId
	}
	return ""
}

type GetLessonsByModuleIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lessons       []*Lesson              `protobuf:"bytes,1,rep,name=lessons,proto3" json:"lessons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLessonsByModuleIdResponse) Reset() {
	*x = GetLessonsByModuleIdResponse{}
	mi := &file_lesson_rpc_lesson_get_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLessonsByModuleIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLessonsByModuleIdResponse) ProtoMessage() {}

func (x *GetLessonsByModuleIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lesson_rpc_lesson_get_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLessonsByModuleIdResponse.ProtoReflect.Descriptor instead.
func (*GetLessonsByModuleIdResponse) Descriptor() ([]byte, []int) {
	return file_lesson_rpc_lesson_get_proto_rawDescGZIP(), []int{1}
}

func (x *GetLessonsByModuleIdResponse) GetLessons() []*Lesson {
	if x != nil {
		return x.Lessons
	}
	return nil
}

type GetLessonByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLessonByIdRequest) Reset() {
	*x = GetLessonByIdRequest{}
	mi := &file_lesson_rpc_lesson_get_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLessonByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLessonByIdRequest) ProtoMessage() {}

func (x *GetLessonByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lesson_rpc_lesson_get_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLessonByIdRequest.ProtoReflect.Descriptor instead.
func (*GetLessonByIdRequest) Descriptor() ([]byte, []int) {
	return file_lesson_rpc_lesson_get_proto_rawDescGZIP(), []int{2}
}

func (x *GetLessonByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetLessonByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lesson        *Lesson                `protobuf:"bytes,1,opt,name=lesson,proto3" json:"lesson,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLessonByIdResponse) Reset() {
	*x = GetLessonByIdResponse{}
	mi := &file_lesson_rpc_lesson_get_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLessonByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLessonByIdResponse) ProtoMessage() {}

func (x *GetLessonByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lesson_rpc_lesson_get_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLessonByIdResponse.ProtoReflect.Descriptor instead.
func (*GetLessonByIdResponse) Descriptor() ([]byte, []int) {
	return file_lesson_rpc_lesson_get_proto_rawDescGZIP(), []int{3}
}

func (x *GetLessonByIdResponse) GetLesson() *Lesson {
	if x != nil {
		return x.Lesson
	}
	return nil
}

var File_lesson_rpc_lesson_get_proto protoreflect.FileDescriptor

const file_lesson_rpc_lesson_get_proto_rawDesc = "" +
	"\n" +
	"\x1blesson/rpc_lesson_get.proto\x12\n" +
	"lms.lesson\x1a\x13lesson/lesson.proto\":\n" +
	"\x1bGetLessonsByModuleIdRequest\x12\x1b\n" +
	"\tmodule_id\x18\x01 \x01(\tR\bmoduleId\"L\n" +
	"\x1cGetLessonsByModuleIdResponse\x12,\n" +
	"\alessons\x18\x01 \x03(\v2\x12.lms.lesson.LessonR\alessons\"&\n" +
	"\x14GetLessonByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"C\n" +
	"\x15GetLessonByIdResponse\x12*\n" +
	"\x06lesson\x18\x01 \x01(\v2\x12.lms.lesson.LessonR\x06lessonB<Z:github.com/multi-tenant-cms-golang/lms-sys/protogen/lessonb\x06proto3"

var (
	file_lesson_rpc_lesson_get_proto_rawDescOnce sync.Once
	file_lesson_rpc_lesson_get_proto_rawDescData []byte
)

func file_lesson_rpc_lesson_get_proto_rawDescGZIP() []byte {
	file_lesson_rpc_lesson_get_proto_rawDescOnce.Do(func() {
		file_lesson_rpc_lesson_get_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lesson_rpc_lesson_get_proto_rawDesc), len(file_lesson_rpc_lesson_get_proto_rawDesc)))
	})
	return file_lesson_rpc_lesson_get_proto_rawDescData
}

var file_lesson_rpc_lesson_get_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_lesson_rpc_lesson_get_proto_goTypes = []any{
	(*GetLessonsByModuleIdRequest)(nil),  // 0: lms.lesson.GetLessonsByModuleIdRequest
	(*GetLessonsByModuleIdResponse)(nil), // 1: lms.lesson.GetLessonsByModuleIdResponse
	(*GetLessonByIdRequest)(nil),         // 2: lms.lesson.GetLessonByIdRequest
	(*GetLessonByIdResponse)(nil),        // 3: lms.lesson.GetLessonByIdResponse
	(*Lesson)(nil),                       // 4: lms.lesson.Lesson
}
var file_lesson_rpc_lesson_get_proto_depIdxs = []int32{
	4, // 0: lms.lesson.GetLessonsByModuleIdResponse.lessons:type_name -> lms.lesson.Lesson
	4, // 1: lms.lesson.GetLessonByIdResponse.lesson:type_name -> lms.lesson.Lesson
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_lesson_rpc_lesson_get_proto_init() }
func file_lesson_rpc_lesson_get_proto_init() {
	if File_lesson_rpc_lesson_get_proto != nil {
		return
	}
	file_lesson_lesson_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lesson_rpc_lesson_get_proto_rawDesc), len(file_lesson_rpc_lesson_get_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lesson_rpc_lesson_get_proto_goTypes,
		DependencyIndexes: file_lesson_rpc_lesson_get_proto_depIdxs,
		MessageInfos:      file_lesson_rpc_lesson_get_proto_msgTypes,
	}.Build()
	File_lesson_rpc_lesson_get_proto = out.File
	file_lesson_rpc_lesson_get_proto_goTypes = nil
	file_lesson_rpc_lesson_get_proto_depIdxs = nil
}
