// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: lesson/service.lesson.proto

package lesson

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_lesson_service_lesson_proto protoreflect.FileDescriptor

const file_lesson_service_lesson_proto_rawDesc = "" +
	"\n" +
	"\x1blesson/service.lesson.proto\x12\n" +
	"lms.lesson\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1blesson/rpc_lesson_get.proto\x1a\x1elesson/rpc_lesson_create.proto\x1a\x1elesson/rpc_lesson_update.proto\x1a\x1elesson/rpc_lesson_delete.proto2\xe5\x04\n" +
	"\rLessonService\x12m\n" +
	"\fCreateLesson\x12\x1f.lms.lesson.CreateLessonRequest\x1a .lms.lesson.CreateLessonResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/lms/v1/lessons\x12r\n" +
	"\rGetLessonById\x12 .lms.lesson.GetLessonByIdRequest\x1a!.lms.lesson.GetLessonByIdResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/lms/v1/lessons/{id}\x12\x8d\x01\n" +
	"\x17GetAllLessonsByModuleId\x12'.lms.lesson.GetLessonsByModuleIdRequest\x1a(.lms.lesson.GetLessonsByModuleIdResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/lms/v1/modules/lessons\x12r\n" +
	"\fUpdateLesson\x12\x1f.lms.lesson.UpdateLessonRequest\x1a .lms.lesson.UpdateLessonResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\x1a\x14/lms/v1/lessons/{id}\x12m\n" +
	"\rDeleteLessons\x12 .lms.lesson.DeleteLessonsRequest\x1a!.lms.lesson.DeleteLessonsResponse\"\x17\x82\xd3\xe4\x93\x02\x11*\x0f/lms/v1/lessonsB\xaf\x03\x92A\xef\x02\x12\xd4\x01\n" +
	"\x14LMS Lesson Endpoints\x121APIs for lesson in the Learning Management System\"D\n" +
	"\bLMS Team\x12\x1fhttps://lms.example.com/support\x1a\x17support@lms.example.com*>\n" +
	"\n" +
	"Apache 2.0\x120https://www.apache.org/licenses/LICENSE-2.0.html2\x031.0\x1a\x0elocalhost:8086\"\x03/v1*\x02\x02\x012\x10application/json:\x10application/jsonZK\n" +
	"I\n" +
	"\x06Bearer\x12?\b\x02\x12*Authentication token, prefixed with Bearer\x1a\rAuthorization \x02b\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00Z:github.com/multi-tenant-cms-golang/lms-sys/protogen/lessonb\x06proto3"

var file_lesson_service_lesson_proto_goTypes = []any{
	(*CreateLessonRequest)(nil),          // 0: lms.lesson.CreateLessonRequest
	(*GetLessonByIdRequest)(nil),         // 1: lms.lesson.GetLessonByIdRequest
	(*GetLessonsByModuleIdRequest)(nil),  // 2: lms.lesson.GetLessonsByModuleIdRequest
	(*UpdateLessonRequest)(nil),          // 3: lms.lesson.UpdateLessonRequest
	(*DeleteLessonsRequest)(nil),         // 4: lms.lesson.DeleteLessonsRequest
	(*CreateLessonResponse)(nil),         // 5: lms.lesson.CreateLessonResponse
	(*GetLessonByIdResponse)(nil),        // 6: lms.lesson.GetLessonByIdResponse
	(*GetLessonsByModuleIdResponse)(nil), // 7: lms.lesson.GetLessonsByModuleIdResponse
	(*UpdateLessonResponse)(nil),         // 8: lms.lesson.UpdateLessonResponse
	(*DeleteLessonsResponse)(nil),        // 9: lms.lesson.DeleteLessonsResponse
}
var file_lesson_service_lesson_proto_depIdxs = []int32{
	0, // 0: lms.lesson.LessonService.CreateLesson:input_type -> lms.lesson.CreateLessonRequest
	1, // 1: lms.lesson.LessonService.GetLessonById:input_type -> lms.lesson.GetLessonByIdRequest
	2, // 2: lms.lesson.LessonService.GetAllLessonsByModuleId:input_type -> lms.lesson.GetLessonsByModuleIdRequest
	3, // 3: lms.lesson.LessonService.UpdateLesson:input_type -> lms.lesson.UpdateLessonRequest
	4, // 4: lms.lesson.LessonService.DeleteLessons:input_type -> lms.lesson.DeleteLessonsRequest
	5, // 5: lms.lesson.LessonService.CreateLesson:output_type -> lms.lesson.CreateLessonResponse
	6, // 6: lms.lesson.LessonService.GetLessonById:output_type -> lms.lesson.GetLessonByIdResponse
	7, // 7: lms.lesson.LessonService.GetAllLessonsByModuleId:output_type -> lms.lesson.GetLessonsByModuleIdResponse
	8, // 8: lms.lesson.LessonService.UpdateLesson:output_type -> lms.lesson.UpdateLessonResponse
	9, // 9: lms.lesson.LessonService.DeleteLessons:output_type -> lms.lesson.DeleteLessonsResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lesson_service_lesson_proto_init() }
func file_lesson_service_lesson_proto_init() {
	if File_lesson_service_lesson_proto != nil {
		return
	}
	file_lesson_rpc_lesson_get_proto_init()
	file_lesson_rpc_lesson_create_proto_init()
	file_lesson_rpc_lesson_update_proto_init()
	file_lesson_rpc_lesson_delete_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lesson_service_lesson_proto_rawDesc), len(file_lesson_service_lesson_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lesson_service_lesson_proto_goTypes,
		DependencyIndexes: file_lesson_service_lesson_proto_depIdxs,
	}.Build()
	File_lesson_service_lesson_proto = out.File
	file_lesson_service_lesson_proto_goTypes = nil
	file_lesson_service_lesson_proto_depIdxs = nil
}
