services:
  cms-main-system:
    build:
      context: backend/cms-sys
      dockerfile: Dockerfile
    networks:
      - whole-system-network
    depends_on:
      vault:
        condition: service_healthy
      postgres-cms:
        condition: service_started
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - APP_ENV=${APP_ENV}
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_FILE_PATH=${LOG_FILE_PATH}
      - LOG_MAX_SIZE=${LOG_MAX_SIZE}
      - LOG_MAX_BACKUPS=${LOG_MAX_BACKUPS}
      - LOG_MAX_AGE=${LOG_MAX_AGE}
      - LOG_COMPRESS=${LOG_COMPRESS}
      - VAULT_ADDR=${VAULT_ADDR}
      - VAULT_TOKEN=${VAULT_TOKEN}
      - LOG_CONSOLE=${LOG_CONSOLE}
    ports:
      - "${PORT}:8080"
    restart: unless-stopped

  vault:
    image: hashicorp/vault:1.15
    container_name: vault
    networks:
      - whole-system-network
    ports:
      - "8200:8200"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=${VAULT_DEV_ROOT_TOKEN_ID}
      - VAULT_DEV_LISTEN_ADDRESS=${VAULT_DEV_LISTEN_ADDRESS}
    volumes:
      - ./vault-init.sh:/vault-init.sh
      - ./rsa:/vault/keys
    entrypoint: /bin/sh
    command: -c "vault server -dev & sleep 5 && sh /vault-init.sh && tail -f /dev/null"
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  postgres-cms:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres-cms:/var/lib/postgresql/data
    networks:
      - whole-system-network
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-lms:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=lms_db
      - POSTGRES_USER=lms_user
      - POSTGRES_PASSWORD=lms_password
    volumes:
      - postgres-lms:/var/lib/postgresql/data
    networks:
      - whole-system-network
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lms_user -d lms_db"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  whole-system-network:
    driver: bridge

volumes:
  postgres-cms:
    driver: local
  postgres-lms:
    driver: local