### Register a new user
POST http://localhost:8086/lms/v1/auth/register
accept: application/json
X-Organisation: Swand
Content-Type: application/json

{
  "username": "SwanhtetAungphyo",
  "email": "swanhtetaundgp@gmail.com",
  "password": "SwanHtet12@",
  "address": "Swan Krakow",
  "phoneNumber": "48608422691",
  "mfaVerificationOption": true
}


### Write http test in here