// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: module/module.proto

package modules

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Module struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModuleId      string                 `protobuf:"bytes,1,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	ModuleName    string                 `protobuf:"bytes,2,opt,name=module_name,json=moduleName,proto3" json:"module_name,omitempty"`
	CourseId      string                 `protobuf:"bytes,3,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Module) Reset() {
	*x = Module{}
	mi := &file_modules_module_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Module) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Module) ProtoMessage() {}

func (x *Module) ProtoReflect() protoreflect.Message {
	mi := &file_modules_module_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Module.ProtoReflect.Descriptor instead.
func (*Module) Descriptor() ([]byte, []int) {
	return file_modules_module_proto_rawDescGZIP(), []int{0}
}

func (x *Module) GetModuleId() string {
	if x != nil {
		return x.ModuleId
	}
	return ""
}

func (x *Module) GetModuleName() string {
	if x != nil {
		return x.ModuleName
	}
	return ""
}

func (x *Module) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *Module) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Module) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Module) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_modules_module_proto protoreflect.FileDescriptor

const file_modules_module_proto_rawDesc = "" +
	"\n" +
	"\x14modules/module.proto\x12\vlms.module\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfb\x01\n" +
	"\x06Module\x12\x1b\n" +
	"\tmodule_id\x18\x01 \x01(\tR\bmoduleId\x12\x1f\n" +
	"\vmodule_name\x18\x02 \x01(\tR\n" +
	"moduleName\x12\x1b\n" +
	"\tcourse_id\x18\x03 \x01(\tR\bcourseId\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB>Z<github.com/multi-tenant-cms-golang/lms-sys/protogen/modulesb\x06proto3"

var (
	file_modules_module_proto_rawDescOnce sync.Once
	file_modules_module_proto_rawDescData []byte
)

func file_modules_module_proto_rawDescGZIP() []byte {
	file_modules_module_proto_rawDescOnce.Do(func() {
		file_modules_module_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_modules_module_proto_rawDesc), len(file_modules_module_proto_rawDesc)))
	})
	return file_modules_module_proto_rawDescData
}

var file_modules_module_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_modules_module_proto_goTypes = []any{
	(*Module)(nil),                // 0: lms.module.Module
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_modules_module_proto_depIdxs = []int32{
	1, // 0: lms.module.Module.created_at:type_name -> google.protobuf.Timestamp
	1, // 1: lms.module.Module.updated_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_modules_module_proto_init() }
func file_modules_module_proto_init() {
	if File_modules_module_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_modules_module_proto_rawDesc), len(file_modules_module_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_modules_module_proto_goTypes,
		DependencyIndexes: file_modules_module_proto_depIdxs,
		MessageInfos:      file_modules_module_proto_msgTypes,
	}.Build()
	File_modules_module_proto = out.File
	file_modules_module_proto_goTypes = nil
	file_modules_module_proto_depIdxs = nil
}
