// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: modules/rpc_list_modules.proto

package modules

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListModulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Modules       []*Module              `protobuf:"bytes,1,rep,name=modules,proto3" json:"modules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModulesResponse) Reset() {
	*x = ListModulesResponse{}
	mi := &file_modules_rpc_list_modules_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModulesResponse) ProtoMessage() {}

func (x *ListModulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_modules_rpc_list_modules_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModulesResponse.ProtoReflect.Descriptor instead.
func (*ListModulesResponse) Descriptor() ([]byte, []int) {
	return file_modules_rpc_list_modules_proto_rawDescGZIP(), []int{0}
}

func (x *ListModulesResponse) GetModules() []*Module {
	if x != nil {
		return x.Modules
	}
	return nil
}

var File_modules_rpc_list_modules_proto protoreflect.FileDescriptor

const file_modules_rpc_list_modules_proto_rawDesc = "" +
	"\n" +
	"\x1emodules/rpc_list_modules.proto\x12\vlms.modules\x1a\x14modules/module.proto\"D\n" +
	"\x13ListModulesResponse\x12-\n" +
	"\amodules\x18\x01 \x03(\v2\x13.lms.modules.ModuleR\amodulesB>Z<github.com/multi-tenants-cms-golang/lms-sys/protogen/modulesb\x06proto3"

var (
	file_modules_rpc_list_modules_proto_rawDescOnce sync.Once
	file_modules_rpc_list_modules_proto_rawDescData []byte
)

func file_modules_rpc_list_modules_proto_rawDescGZIP() []byte {
	file_modules_rpc_list_modules_proto_rawDescOnce.Do(func() {
		file_modules_rpc_list_modules_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_modules_rpc_list_modules_proto_rawDesc), len(file_modules_rpc_list_modules_proto_rawDesc)))
	})
	return file_modules_rpc_list_modules_proto_rawDescData
}

var file_modules_rpc_list_modules_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_modules_rpc_list_modules_proto_goTypes = []any{
	(*ListModulesResponse)(nil), // 0: lms.modules.ListModulesResponse
	(*Module)(nil),              // 1: lms.modules.Module
}
var file_modules_rpc_list_modules_proto_depIdxs = []int32{
	1, // 0: lms.modules.ListModulesResponse.modules:type_name -> lms.modules.Module
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_modules_rpc_list_modules_proto_init() }
func file_modules_rpc_list_modules_proto_init() {
	if File_modules_rpc_list_modules_proto != nil {
		return
	}
	file_modules_module_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_modules_rpc_list_modules_proto_rawDesc), len(file_modules_rpc_list_modules_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_modules_rpc_list_modules_proto_goTypes,
		DependencyIndexes: file_modules_rpc_list_modules_proto_depIdxs,
		MessageInfos:      file_modules_rpc_list_modules_proto_msgTypes,
	}.Build()
	File_modules_rpc_list_modules_proto = out.File
	file_modules_rpc_list_modules_proto_goTypes = nil
	file_modules_rpc_list_modules_proto_depIdxs = nil
}
