/*
CMS Multi-Tenant System API

API documentation for the CMS Multi-Tenant System with MFA support

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MFALoginRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MFALoginRequest{}

// MFALoginRequest struct for MFALoginRequest
type MFALoginRequest struct {
	Email string `json:"email"`
	Password string `json:"password"`
	// 6-digit MFA code from authenticator app
	MfaCode string `json:"mfa_code"`
}

type _MFALoginRequest MFALoginRequest

// NewMFALoginRequest instantiates a new MFALoginRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMFALoginRequest(email string, password string, mfaCode string) *MFALoginRequest {
	this := MFALoginRequest{}
	this.Email = email
	this.Password = password
	this.MfaCode = mfaCode
	return &this
}

// NewMFALoginRequestWithDefaults instantiates a new MFALoginRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMFALoginRequestWithDefaults() *MFALoginRequest {
	this := MFALoginRequest{}
	return &this
}

// GetEmail returns the Email field value
func (o *MFALoginRequest) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *MFALoginRequest) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *MFALoginRequest) SetEmail(v string) {
	o.Email = v
}

// GetPassword returns the Password field value
func (o *MFALoginRequest) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *MFALoginRequest) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *MFALoginRequest) SetPassword(v string) {
	o.Password = v
}

// GetMfaCode returns the MfaCode field value
func (o *MFALoginRequest) GetMfaCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MfaCode
}

// GetMfaCodeOk returns a tuple with the MfaCode field value
// and a boolean to check if the value has been set.
func (o *MFALoginRequest) GetMfaCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MfaCode, true
}

// SetMfaCode sets field value
func (o *MFALoginRequest) SetMfaCode(v string) {
	o.MfaCode = v
}

func (o MFALoginRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MFALoginRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["email"] = o.Email
	toSerialize["password"] = o.Password
	toSerialize["mfa_code"] = o.MfaCode
	return toSerialize, nil
}

func (o *MFALoginRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
		"password",
		"mfa_code",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMFALoginRequest := _MFALoginRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMFALoginRequest)

	if err != nil {
		return err
	}

	*o = MFALoginRequest(varMFALoginRequest)

	return err
}

type NullableMFALoginRequest struct {
	value *MFALoginRequest
	isSet bool
}

func (v NullableMFALoginRequest) Get() *MFALoginRequest {
	return v.value
}

func (v *NullableMFALoginRequest) Set(val *MFALoginRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableMFALoginRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableMFALoginRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMFALoginRequest(val *MFALoginRequest) *NullableMFALoginRequest {
	return &NullableMFALoginRequest{value: val, isSet: true}
}

func (v NullableMFALoginRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMFALoginRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


