/*
CMS Multi-Tenant System API

API documentation for the CMS Multi-Tenant System with MFA support

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the OwnerResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OwnerResponse{}

// OwnerResponse struct for OwnerResponse
type OwnerResponse struct {
	Id *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	Email *string `json:"email,omitempty"`
	Role *string `json:"role,omitempty"`
	NameSpace *string `json:"name_space,omitempty"`
	Verified *bool `json:"verified,omitempty"`
}

// NewOwnerResponse instantiates a new OwnerResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOwnerResponse() *OwnerResponse {
	this := OwnerResponse{}
	return &this
}

// NewOwnerResponseWithDefaults instantiates a new OwnerResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOwnerResponseWithDefaults() *OwnerResponse {
	this := OwnerResponse{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *OwnerResponse) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OwnerResponse) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *OwnerResponse) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *OwnerResponse) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *OwnerResponse) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OwnerResponse) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *OwnerResponse) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *OwnerResponse) SetName(v string) {
	o.Name = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *OwnerResponse) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OwnerResponse) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *OwnerResponse) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *OwnerResponse) SetEmail(v string) {
	o.Email = &v
}

// GetRole returns the Role field value if set, zero value otherwise.
func (o *OwnerResponse) GetRole() string {
	if o == nil || IsNil(o.Role) {
		var ret string
		return ret
	}
	return *o.Role
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OwnerResponse) GetRoleOk() (*string, bool) {
	if o == nil || IsNil(o.Role) {
		return nil, false
	}
	return o.Role, true
}

// HasRole returns a boolean if a field has been set.
func (o *OwnerResponse) HasRole() bool {
	if o != nil && !IsNil(o.Role) {
		return true
	}

	return false
}

// SetRole gets a reference to the given string and assigns it to the Role field.
func (o *OwnerResponse) SetRole(v string) {
	o.Role = &v
}

// GetNameSpace returns the NameSpace field value if set, zero value otherwise.
func (o *OwnerResponse) GetNameSpace() string {
	if o == nil || IsNil(o.NameSpace) {
		var ret string
		return ret
	}
	return *o.NameSpace
}

// GetNameSpaceOk returns a tuple with the NameSpace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OwnerResponse) GetNameSpaceOk() (*string, bool) {
	if o == nil || IsNil(o.NameSpace) {
		return nil, false
	}
	return o.NameSpace, true
}

// HasNameSpace returns a boolean if a field has been set.
func (o *OwnerResponse) HasNameSpace() bool {
	if o != nil && !IsNil(o.NameSpace) {
		return true
	}

	return false
}

// SetNameSpace gets a reference to the given string and assigns it to the NameSpace field.
func (o *OwnerResponse) SetNameSpace(v string) {
	o.NameSpace = &v
}

// GetVerified returns the Verified field value if set, zero value otherwise.
func (o *OwnerResponse) GetVerified() bool {
	if o == nil || IsNil(o.Verified) {
		var ret bool
		return ret
	}
	return *o.Verified
}

// GetVerifiedOk returns a tuple with the Verified field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OwnerResponse) GetVerifiedOk() (*bool, bool) {
	if o == nil || IsNil(o.Verified) {
		return nil, false
	}
	return o.Verified, true
}

// HasVerified returns a boolean if a field has been set.
func (o *OwnerResponse) HasVerified() bool {
	if o != nil && !IsNil(o.Verified) {
		return true
	}

	return false
}

// SetVerified gets a reference to the given bool and assigns it to the Verified field.
func (o *OwnerResponse) SetVerified(v bool) {
	o.Verified = &v
}

func (o OwnerResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OwnerResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.Role) {
		toSerialize["role"] = o.Role
	}
	if !IsNil(o.NameSpace) {
		toSerialize["name_space"] = o.NameSpace
	}
	if !IsNil(o.Verified) {
		toSerialize["verified"] = o.Verified
	}
	return toSerialize, nil
}

type NullableOwnerResponse struct {
	value *OwnerResponse
	isSet bool
}

func (v NullableOwnerResponse) Get() *OwnerResponse {
	return v.value
}

func (v *NullableOwnerResponse) Set(val *OwnerResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableOwnerResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableOwnerResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOwnerResponse(val *OwnerResponse) *NullableOwnerResponse {
	return &NullableOwnerResponse{value: val, isSet: true}
}

func (v NullableOwnerResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOwnerResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


