/*
CMS Multi-Tenant System API

API documentation for the CMS Multi-Tenant System with MFA support

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PaginateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginateRequest{}

// PaginateRequest struct for PaginateRequest
type PaginateRequest struct {
	Page *int32 `json:"page,omitempty"`
	Limit *int32 `json:"limit,omitempty"`
}

// NewPaginateRequest instantiates a new PaginateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginateRequest() *PaginateRequest {
	this := PaginateRequest{}
	return &this
}

// NewPaginateRequestWithDefaults instantiates a new PaginateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginateRequestWithDefaults() *PaginateRequest {
	this := PaginateRequest{}
	return &this
}

// GetPage returns the Page field value if set, zero value otherwise.
func (o *PaginateRequest) GetPage() int32 {
	if o == nil || IsNil(o.Page) {
		var ret int32
		return ret
	}
	return *o.Page
}

// GetPageOk returns a tuple with the Page field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginateRequest) GetPageOk() (*int32, bool) {
	if o == nil || IsNil(o.Page) {
		return nil, false
	}
	return o.Page, true
}

// HasPage returns a boolean if a field has been set.
func (o *PaginateRequest) HasPage() bool {
	if o != nil && !IsNil(o.Page) {
		return true
	}

	return false
}

// SetPage gets a reference to the given int32 and assigns it to the Page field.
func (o *PaginateRequest) SetPage(v int32) {
	o.Page = &v
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *PaginateRequest) GetLimit() int32 {
	if o == nil || IsNil(o.Limit) {
		var ret int32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginateRequest) GetLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.Limit) {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *PaginateRequest) HasLimit() bool {
	if o != nil && !IsNil(o.Limit) {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int32 and assigns it to the Limit field.
func (o *PaginateRequest) SetLimit(v int32) {
	o.Limit = &v
}

func (o PaginateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaginateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Page) {
		toSerialize["page"] = o.Page
	}
	if !IsNil(o.Limit) {
		toSerialize["limit"] = o.Limit
	}
	return toSerialize, nil
}

type NullablePaginateRequest struct {
	value *PaginateRequest
	isSet bool
}

func (v NullablePaginateRequest) Get() *PaginateRequest {
	return v.value
}

func (v *NullablePaginateRequest) Set(val *PaginateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginateRequest(val *PaginateRequest) *NullablePaginateRequest {
	return &NullablePaginateRequest{value: val, isSet: true}
}

func (v NullablePaginateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


