/*
CMS Multi-Tenant System API

API documentation for the CMS Multi-Tenant System with MFA support

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MFAVerificationRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MFAVerificationRequest{}

// MFAVerificationRequest struct for MFAVerificationRequest
type MFAVerificationRequest struct {
	// Temporary token ID from setup
	TokenId int32 `json:"token_id"`
	// 6-digit verification code from authenticator app
	Code string `json:"code"`
}

type _MFAVerificationRequest MFAVerificationRequest

// NewMFAVerificationRequest instantiates a new MFAVerificationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMFAVerificationRequest(tokenId int32, code string) *MFAVerificationRequest {
	this := MFAVerificationRequest{}
	this.TokenId = tokenId
	this.Code = code
	return &this
}

// NewMFAVerificationRequestWithDefaults instantiates a new MFAVerificationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMFAVerificationRequestWithDefaults() *MFAVerificationRequest {
	this := MFAVerificationRequest{}
	return &this
}

// GetTokenId returns the TokenId field value
func (o *MFAVerificationRequest) GetTokenId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TokenId
}

// GetTokenIdOk returns a tuple with the TokenId field value
// and a boolean to check if the value has been set.
func (o *MFAVerificationRequest) GetTokenIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TokenId, true
}

// SetTokenId sets field value
func (o *MFAVerificationRequest) SetTokenId(v int32) {
	o.TokenId = v
}

// GetCode returns the Code field value
func (o *MFAVerificationRequest) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *MFAVerificationRequest) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *MFAVerificationRequest) SetCode(v string) {
	o.Code = v
}

func (o MFAVerificationRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MFAVerificationRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["token_id"] = o.TokenId
	toSerialize["code"] = o.Code
	return toSerialize, nil
}

func (o *MFAVerificationRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"token_id",
		"code",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMFAVerificationRequest := _MFAVerificationRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMFAVerificationRequest)

	if err != nil {
		return err
	}

	*o = MFAVerificationRequest(varMFAVerificationRequest)

	return err
}

type NullableMFAVerificationRequest struct {
	value *MFAVerificationRequest
	isSet bool
}

func (v NullableMFAVerificationRequest) Get() *MFAVerificationRequest {
	return v.value
}

func (v *NullableMFAVerificationRequest) Set(val *MFAVerificationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableMFAVerificationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableMFAVerificationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMFAVerificationRequest(val *MFAVerificationRequest) *NullableMFAVerificationRequest {
	return &NullableMFAVerificationRequest{value: val, isSet: true}
}

func (v NullableMFAVerificationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMFAVerificationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


