// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/course/course.proto

package coursepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Course struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title            string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description      string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CategoryId       int64                  `protobuf:"varint,4,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	InstructorId     int64                  `protobuf:"varint,5,opt,name=instructor_id,json=instructorId,proto3" json:"instructor_id,omitempty"`
	OverallRating    int32                  `protobuf:"varint,6,opt,name=overall_rating,json=overallRating,proto3" json:"overall_rating,omitempty"`
	Status           string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	DurationDayCount int32                  `protobuf:"varint,8,opt,name=duration_day_count,json=durationDayCount,proto3" json:"duration_day_count,omitempty"`
	CreatedAt        string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt        string                 `protobuf:"bytes,11,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Course) Reset() {
	*x = Course{}
	mi := &file_proto_course_course_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Course) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Course) ProtoMessage() {}

func (x *Course) ProtoReflect() protoreflect.Message {
	mi := &file_proto_course_course_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Course.ProtoReflect.Descriptor instead.
func (*Course) Descriptor() ([]byte, []int) {
	return file_proto_course_course_proto_rawDescGZIP(), []int{0}
}

func (x *Course) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Course) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Course) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Course) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *Course) GetInstructorId() int64 {
	if x != nil {
		return x.InstructorId
	}
	return 0
}

func (x *Course) GetOverallRating() int32 {
	if x != nil {
		return x.OverallRating
	}
	return 0
}

func (x *Course) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Course) GetDurationDayCount() int32 {
	if x != nil {
		return x.DurationDayCount
	}
	return 0
}

func (x *Course) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Course) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Course) GetDeletedAt() string {
	if x != nil {
		return x.DeletedAt
	}
	return ""
}

var File_proto_course_course_proto protoreflect.FileDescriptor

const file_proto_course_course_proto_rawDesc = "" +
	"\n" +
	"\x19proto/course/course.proto\x12\n" +
	"lms.course\"\xe0\x02\n" +
	"\x06Course\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1f\n" +
	"\vcategory_id\x18\x04 \x01(\x03R\n" +
	"categoryId\x12#\n" +
	"\rinstructor_id\x18\x05 \x01(\x03R\finstructorId\x12%\n" +
	"\x0eoverall_rating\x18\x06 \x01(\x05R\roverallRating\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12,\n" +
	"\x12duration_day_count\x18\b \x01(\x05R\x10durationDayCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"deleted_at\x18\v \x01(\tR\tdeletedAtB_Z]github.com/YeZawHlaing/multi-tenants-cms-golang/backend/lms-main-system/proto/course;coursepbb\x06proto3"

var (
	file_proto_course_course_proto_rawDescOnce sync.Once
	file_proto_course_course_proto_rawDescData []byte
)

func file_proto_course_course_proto_rawDescGZIP() []byte {
	file_proto_course_course_proto_rawDescOnce.Do(func() {
		file_proto_course_course_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_course_course_proto_rawDesc), len(file_proto_course_course_proto_rawDesc)))
	})
	return file_proto_course_course_proto_rawDescData
}

var file_proto_course_course_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_course_course_proto_goTypes = []any{
	(*Course)(nil), // 0: lms.course.Course
}
var file_proto_course_course_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_course_course_proto_init() }
func file_proto_course_course_proto_init() {
	if File_proto_course_course_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_course_course_proto_rawDesc), len(file_proto_course_course_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_course_course_proto_goTypes,
		DependencyIndexes: file_proto_course_course_proto_depIdxs,
		MessageInfos:      file_proto_course_course_proto_msgTypes,
	}.Build()
	File_proto_course_course_proto = out.File
	file_proto_course_course_proto_goTypes = nil
	file_proto_course_course_proto_depIdxs = nil
}
