// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: tenant/service.tenants.proto

package tenant

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_tenant_service_tenants_proto protoreflect.FileDescriptor

const file_tenant_service_tenants_proto_rawDesc = "" +
	"\n" +
	"\x1ctenant/service.tenants.proto\x12\vlms.tenants\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1ftenant/rpc_tenants_create.proto2\xa7\x01\n" +
	"\rTenantService\x12\x95\x01\n" +
	"\fCreateTenant\x12 .lms.tenants.CreateTenantRequest\x1a!.lms.tenants.CreateTenantResponse\"@\x92A$\x12\rCreate Tenant\x1a\x13Create a new tenant\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/lms/v1/tenantB<Z:github.com/multi-tenant-cms-golang/lms-sys/protogen/tenantb\x06proto3"

var file_tenant_service_tenants_proto_goTypes = []any{
	(*CreateTenantRequest)(nil),  // 0: lms.tenants.CreateTenantRequest
	(*CreateTenantResponse)(nil), // 1: lms.tenants.CreateTenantResponse
}
var file_tenant_service_tenants_proto_depIdxs = []int32{
	0, // 0: lms.tenants.TenantService.CreateTenant:input_type -> lms.tenants.CreateTenantRequest
	1, // 1: lms.tenants.TenantService.CreateTenant:output_type -> lms.tenants.CreateTenantResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tenant_service_tenants_proto_init() }
func file_tenant_service_tenants_proto_init() {
	if File_tenant_service_tenants_proto != nil {
		return
	}
	file_tenant_rpc_tenants_create_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tenant_service_tenants_proto_rawDesc), len(file_tenant_service_tenants_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tenant_service_tenants_proto_goTypes,
		DependencyIndexes: file_tenant_service_tenants_proto_depIdxs,
	}.Build()
	File_tenant_service_tenants_proto = out.File
	file_tenant_service_tenants_proto_goTypes = nil
	file_tenant_service_tenants_proto_depIdxs = nil
}
