// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.21.12
// source: authentication/rpc_mfa_setup.proto

package authentication

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MFASetUpRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DomainEmail string `protobuf:"bytes,1,opt,name=domain_email,json=domainEmail,proto3" json:"domain_email,omitempty"`
}

func (x *MFASetUpRequest) Reset() {
	*x = MFASetUpRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authentication_rpc_mfa_setup_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MFASetUpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MFASetUpRequest) ProtoMessage() {}

func (x *MFASetUpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_rpc_mfa_setup_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MFASetUpRequest.ProtoReflect.Descriptor instead.
func (*MFASetUpRequest) Descriptor() ([]byte, []int) {
	return file_authentication_rpc_mfa_setup_proto_rawDescGZIP(), []int{0}
}

func (x *MFASetUpRequest) GetDomainEmail() string {
	if x != nil {
		return x.DomainEmail
	}
	return ""
}

type MFASetUpResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MfaUrl      string `protobuf:"bytes,3,opt,name=mfa_url,json=mfaUrl,proto3" json:"mfa_url,omitempty"`
	PhotoString string `protobuf:"bytes,1,opt,name=photoString,proto3" json:"photoString,omitempty"`
	ManualEntry string `protobuf:"bytes,2,opt,name=manualEntry,proto3" json:"manualEntry,omitempty"`
}

func (x *MFASetUpResponse) Reset() {
	*x = MFASetUpResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authentication_rpc_mfa_setup_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MFASetUpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MFASetUpResponse) ProtoMessage() {}

func (x *MFASetUpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_rpc_mfa_setup_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MFASetUpResponse.ProtoReflect.Descriptor instead.
func (*MFASetUpResponse) Descriptor() ([]byte, []int) {
	return file_authentication_rpc_mfa_setup_proto_rawDescGZIP(), []int{1}
}

func (x *MFASetUpResponse) GetMfaUrl() string {
	if x != nil {
		return x.MfaUrl
	}
	return ""
}

func (x *MFASetUpResponse) GetPhotoString() string {
	if x != nil {
		return x.PhotoString
	}
	return ""
}

func (x *MFASetUpResponse) GetManualEntry() string {
	if x != nil {
		return x.ManualEntry
	}
	return ""
}

var File_authentication_rpc_mfa_setup_proto protoreflect.FileDescriptor

var file_authentication_rpc_mfa_setup_proto_rawDesc = []byte{
	0x0a, 0x22, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2f, 0x72, 0x70, 0x63, 0x5f, 0x6d, 0x66, 0x61, 0x5f, 0x73, 0x65, 0x74, 0x75, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x6c, 0x6d, 0x73, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e,
	0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x34, 0x0a, 0x0f, 0x4d, 0x46, 0x41, 0x53,
	0x65, 0x74, 0x55, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x64,
	0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x5f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x6f,
	0x0a, 0x10, 0x4d, 0x46, 0x41, 0x53, 0x65, 0x74, 0x55, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x6d, 0x66, 0x61, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x66, 0x61, 0x55, 0x72, 0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x70,
	0x68, 0x6f, 0x74, 0x6f, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x20, 0x0a,
	0x0b, 0x6d, 0x61, 0x6e, 0x75, 0x61, 0x6c, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x6d, 0x61, 0x6e, 0x75, 0x61, 0x6c, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x42,
	0x44, 0x5a, 0x42, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x75,
	0x6c, 0x74, 0x69, 0x2d, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x2d, 0x63, 0x6d, 0x73, 0x2d, 0x67,
	0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2f, 0x6c, 0x6d, 0x73, 0x2d, 0x73, 0x79, 0x73, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x67, 0x65, 0x6e, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_authentication_rpc_mfa_setup_proto_rawDescOnce sync.Once
	file_authentication_rpc_mfa_setup_proto_rawDescData = file_authentication_rpc_mfa_setup_proto_rawDesc
)

func file_authentication_rpc_mfa_setup_proto_rawDescGZIP() []byte {
	file_authentication_rpc_mfa_setup_proto_rawDescOnce.Do(func() {
		file_authentication_rpc_mfa_setup_proto_rawDescData = protoimpl.X.CompressGZIP(file_authentication_rpc_mfa_setup_proto_rawDescData)
	})
	return file_authentication_rpc_mfa_setup_proto_rawDescData
}

var file_authentication_rpc_mfa_setup_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_authentication_rpc_mfa_setup_proto_goTypes = []interface{}{
	(*MFASetUpRequest)(nil),  // 0: lms.authentication.MFASetUpRequest
	(*MFASetUpResponse)(nil), // 1: lms.authentication.MFASetUpResponse
}
var file_authentication_rpc_mfa_setup_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_authentication_rpc_mfa_setup_proto_init() }
func file_authentication_rpc_mfa_setup_proto_init() {
	if File_authentication_rpc_mfa_setup_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_authentication_rpc_mfa_setup_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MFASetUpRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_authentication_rpc_mfa_setup_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MFASetUpResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_authentication_rpc_mfa_setup_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_authentication_rpc_mfa_setup_proto_goTypes,
		DependencyIndexes: file_authentication_rpc_mfa_setup_proto_depIdxs,
		MessageInfos:      file_authentication_rpc_mfa_setup_proto_msgTypes,
	}.Build()
	File_authentication_rpc_mfa_setup_proto = out.File
	file_authentication_rpc_mfa_setup_proto_rawDesc = nil
	file_authentication_rpc_mfa_setup_proto_goTypes = nil
	file_authentication_rpc_mfa_setup_proto_depIdxs = nil
}
