// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: authentication/rpc_refresh.proto

package authentication

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_authentication_rpc_refresh_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_rpc_refresh_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_authentication_rpc_refresh_proto_rawDescGZIP(), []int{0}
}

type RefreshTokenResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NewAccessToken string                 `protobuf:"bytes,1,opt,name=new_access_token,json=newAccessToken,proto3" json:"new_access_token,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RefreshTokenResponse) Reset() {
	*x = RefreshTokenResponse{}
	mi := &file_authentication_rpc_refresh_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResponse) ProtoMessage() {}

func (x *RefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_rpc_refresh_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_authentication_rpc_refresh_proto_rawDescGZIP(), []int{1}
}

func (x *RefreshTokenResponse) GetNewAccessToken() string {
	if x != nil {
		return x.NewAccessToken
	}
	return ""
}

var File_authentication_rpc_refresh_proto protoreflect.FileDescriptor

const file_authentication_rpc_refresh_proto_rawDesc = "" +
	"\n" +
	" authentication/rpc_refresh.proto\x12\x12lms.authentication\"\x15\n" +
	"\x13RefreshTokenRequest\"@\n" +
	"\x14RefreshTokenResponse\x12(\n" +
	"\x10new_access_token\x18\x01 \x01(\tR\x0enewAccessTokenBDZBgithub.com/multi-tenant-cms-golang/lms-sys/protogen/authenticationb\x06proto3"

var (
	file_authentication_rpc_refresh_proto_rawDescOnce sync.Once
	file_authentication_rpc_refresh_proto_rawDescData []byte
)

func file_authentication_rpc_refresh_proto_rawDescGZIP() []byte {
	file_authentication_rpc_refresh_proto_rawDescOnce.Do(func() {
		file_authentication_rpc_refresh_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_authentication_rpc_refresh_proto_rawDesc), len(file_authentication_rpc_refresh_proto_rawDesc)))
	})
	return file_authentication_rpc_refresh_proto_rawDescData
}

var file_authentication_rpc_refresh_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_authentication_rpc_refresh_proto_goTypes = []any{
	(*RefreshTokenRequest)(nil),  // 0: lms.authentication.RefreshTokenRequest
	(*RefreshTokenResponse)(nil), // 1: lms.authentication.RefreshTokenResponse
}
var file_authentication_rpc_refresh_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_authentication_rpc_refresh_proto_init() }
func file_authentication_rpc_refresh_proto_init() {
	if File_authentication_rpc_refresh_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_authentication_rpc_refresh_proto_rawDesc), len(file_authentication_rpc_refresh_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_authentication_rpc_refresh_proto_goTypes,
		DependencyIndexes: file_authentication_rpc_refresh_proto_depIdxs,
		MessageInfos:      file_authentication_rpc_refresh_proto_msgTypes,
	}.Build()
	File_authentication_rpc_refresh_proto = out.File
	file_authentication_rpc_refresh_proto_goTypes = nil
	file_authentication_rpc_refresh_proto_depIdxs = nil
}
