// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: authentication/rpc_login.proto

package authentication

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Organisation         string                 `protobuf:"bytes,1,opt,name=organisation,proto3" json:"organisation,omitempty"`
	NamespaceDomainEmail string                 `protobuf:"bytes,2,opt,name=namespace_domain_email,json=namespaceDomainEmail,proto3" json:"namespace_domain_email,omitempty"`
	Password             string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_authentication_rpc_login_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_rpc_login_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_authentication_rpc_login_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetOrganisation() string {
	if x != nil {
		return x.Organisation
	}
	return ""
}

func (x *LoginRequest) GetNamespaceDomainEmail() string {
	if x != nil {
		return x.NamespaceDomainEmail
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	MfaEnable     bool                   `protobuf:"varint,2,opt,name=mfa_enable,json=mfaEnable,proto3" json:"mfa_enable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_authentication_rpc_login_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_rpc_login_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_authentication_rpc_login_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LoginResponse) GetMfaEnable() bool {
	if x != nil {
		return x.MfaEnable
	}
	return false
}

var File_authentication_rpc_login_proto protoreflect.FileDescriptor

const file_authentication_rpc_login_proto_rawDesc = "" +
	"\n" +
	"\x1eauthentication/rpc_login.proto\x12\x12lms.authentication\x1a\x1fgoogle/protobuf/timestamp.proto\"\x84\x01\n" +
	"\fLoginRequest\x12\"\n" +
	"\forganisation\x18\x01 \x01(\tR\forganisation\x124\n" +
	"\x16namespace_domain_email\x18\x02 \x01(\tR\x14namespaceDomainEmail\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"H\n" +
	"\rLoginResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"mfa_enable\x18\x02 \x01(\bR\tmfaEnableBDZBgithub.com/multi-tenant-cms-golang/lms-sys/protogen/authenticationb\x06proto3"

var (
	file_authentication_rpc_login_proto_rawDescOnce sync.Once
	file_authentication_rpc_login_proto_rawDescData []byte
)

func file_authentication_rpc_login_proto_rawDescGZIP() []byte {
	file_authentication_rpc_login_proto_rawDescOnce.Do(func() {
		file_authentication_rpc_login_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_authentication_rpc_login_proto_rawDesc), len(file_authentication_rpc_login_proto_rawDesc)))
	})
	return file_authentication_rpc_login_proto_rawDescData
}

var file_authentication_rpc_login_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_authentication_rpc_login_proto_goTypes = []any{
	(*LoginRequest)(nil),  // 0: lms.authentication.LoginRequest
	(*LoginResponse)(nil), // 1: lms.authentication.LoginResponse
}
var file_authentication_rpc_login_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_authentication_rpc_login_proto_init() }
func file_authentication_rpc_login_proto_init() {
	if File_authentication_rpc_login_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_authentication_rpc_login_proto_rawDesc), len(file_authentication_rpc_login_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_authentication_rpc_login_proto_goTypes,
		DependencyIndexes: file_authentication_rpc_login_proto_depIdxs,
		MessageInfos:      file_authentication_rpc_login_proto_msgTypes,
	}.Build()
	File_authentication_rpc_login_proto = out.File
	file_authentication_rpc_login_proto_goTypes = nil
	file_authentication_rpc_login_proto_depIdxs = nil
}
