// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: authentication/rpc_mfa_setup.proto

package authentication

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MFASetUpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DomainEmail   string                 `protobuf:"bytes,1,opt,name=domain_email,json=domainEmail,proto3" json:"domain_email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MFASetUpRequest) Reset() {
	*x = MFASetUpRequest{}
	mi := &file_authentication_rpc_mfa_setup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MFASetUpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MFASetUpRequest) ProtoMessage() {}

func (x *MFASetUpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_rpc_mfa_setup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MFASetUpRequest.ProtoReflect.Descriptor instead.
func (*MFASetUpRequest) Descriptor() ([]byte, []int) {
	return file_authentication_rpc_mfa_setup_proto_rawDescGZIP(), []int{0}
}

func (x *MFASetUpRequest) GetDomainEmail() string {
	if x != nil {
		return x.DomainEmail
	}
	return ""
}

type MFASetUpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MfaUrl        string                 `protobuf:"bytes,3,opt,name=mfa_url,json=mfaUrl,proto3" json:"mfa_url,omitempty"`
	PhotoString   string                 `protobuf:"bytes,1,opt,name=photoString,proto3" json:"photoString,omitempty"`
	ManualEntry   string                 `protobuf:"bytes,2,opt,name=manualEntry,proto3" json:"manualEntry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MFASetUpResponse) Reset() {
	*x = MFASetUpResponse{}
	mi := &file_authentication_rpc_mfa_setup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MFASetUpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MFASetUpResponse) ProtoMessage() {}

func (x *MFASetUpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_rpc_mfa_setup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MFASetUpResponse.ProtoReflect.Descriptor instead.
func (*MFASetUpResponse) Descriptor() ([]byte, []int) {
	return file_authentication_rpc_mfa_setup_proto_rawDescGZIP(), []int{1}
}

func (x *MFASetUpResponse) GetMfaUrl() string {
	if x != nil {
		return x.MfaUrl
	}
	return ""
}

func (x *MFASetUpResponse) GetPhotoString() string {
	if x != nil {
		return x.PhotoString
	}
	return ""
}

func (x *MFASetUpResponse) GetManualEntry() string {
	if x != nil {
		return x.ManualEntry
	}
	return ""
}

var File_authentication_rpc_mfa_setup_proto protoreflect.FileDescriptor

const file_authentication_rpc_mfa_setup_proto_rawDesc = "" +
	"\n" +
	"\"authentication/rpc_mfa_setup.proto\x12\x12lms.authentication\"4\n" +
	"\x0fMFASetUpRequest\x12!\n" +
	"\fdomain_email\x18\x01 \x01(\tR\vdomainEmail\"o\n" +
	"\x10MFASetUpResponse\x12\x17\n" +
	"\amfa_url\x18\x03 \x01(\tR\x06mfaUrl\x12 \n" +
	"\vphotoString\x18\x01 \x01(\tR\vphotoString\x12 \n" +
	"\vmanualEntry\x18\x02 \x01(\tR\vmanualEntryBDZBgithub.com/multi-tenant-cms-golang/lms-sys/protogen/authenticationb\x06proto3"

var (
	file_authentication_rpc_mfa_setup_proto_rawDescOnce sync.Once
	file_authentication_rpc_mfa_setup_proto_rawDescData []byte
)

func file_authentication_rpc_mfa_setup_proto_rawDescGZIP() []byte {
	file_authentication_rpc_mfa_setup_proto_rawDescOnce.Do(func() {
		file_authentication_rpc_mfa_setup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_authentication_rpc_mfa_setup_proto_rawDesc), len(file_authentication_rpc_mfa_setup_proto_rawDesc)))
	})
	return file_authentication_rpc_mfa_setup_proto_rawDescData
}

var file_authentication_rpc_mfa_setup_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_authentication_rpc_mfa_setup_proto_goTypes = []any{
	(*MFASetUpRequest)(nil),  // 0: lms.authentication.MFASetUpRequest
	(*MFASetUpResponse)(nil), // 1: lms.authentication.MFASetUpResponse
}
var file_authentication_rpc_mfa_setup_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_authentication_rpc_mfa_setup_proto_init() }
func file_authentication_rpc_mfa_setup_proto_init() {
	if File_authentication_rpc_mfa_setup_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_authentication_rpc_mfa_setup_proto_rawDesc), len(file_authentication_rpc_mfa_setup_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_authentication_rpc_mfa_setup_proto_goTypes,
		DependencyIndexes: file_authentication_rpc_mfa_setup_proto_depIdxs,
		MessageInfos:      file_authentication_rpc_mfa_setup_proto_msgTypes,
	}.Build()
	File_authentication_rpc_mfa_setup_proto = out.File
	file_authentication_rpc_mfa_setup_proto_goTypes = nil
	file_authentication_rpc_mfa_setup_proto_depIdxs = nil
}
