// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: module/service.module.proto

package module

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_module_service_module_proto protoreflect.FileDescriptor

const file_module_service_module_proto_rawDesc = "" +
	"\n" +
	"\x1bmodule/service.module.proto\x12\vlms.modules\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1emodule/rpc_create_module.proto\x1a\x1fmodule/rpc_delete_modules.proto\x1a\x1bmodule/rpc_get_module.proto\x1a\x1dmodule/rpc_list_modules.proto\x1a\x1emodule/rpc_update_module.proto2\x90\x06\n" +
	"\rModuleService\x12\x95\x01\n" +
	"\fCreateModule\x12 .lms.modules.CreateModuleRequest\x1a!.lms.modules.CreateModuleResponse\"@\x92A$\x12\rCreate module\x1a\x13Create a new module\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/lms/v1/module\x12\xa7\x01\n" +
	"\fUpdateModule\x12 .lms.modules.UpdateModuleRequest\x1a!.lms.modules.UpdateModuleResponse\"R\x92A*\x12\rUpdate module\x1a\x19Update an existing module\x82\xd3\xe4\x93\x02\x1f:\x01*\x1a\x1a/lms/v1/module/{module_id}\x12\xa2\x01\n" +
	"\rDeleteModules\x12!.lms.modules.DeleteModulesRequest\x1a\".lms.modules.DeleteModulesResponse\"J\x92A1\x12\rDelete module\x1a Delete single or multiple module\x82\xd3\xe4\x93\x02\x10*\x0e/lms/v1/module\x12\x87\x01\n" +
	"\vListModules\x12\x16.google.protobuf.Empty\x1a .lms.modules.ListModulesResponse\">\x92A%\x12\x0eGet all module\x1a\x13List/Get all module\x82\xd3\xe4\x93\x02\x10\x12\x0e/lms/v1/module\x12\x8d\x01\n" +
	"\tGetModule\x12\x1d.lms.modules.GetModuleRequest\x1a\x1e.lms.modules.GetModuleResponse\"A\x92A\x1c\x12\fGet a module\x1a\fGet a module\x82\xd3\xe4\x93\x02\x1c\x12\x1a/lms/v1/module/{module_id}B<Z:github.com/multi-tenant-cms-golang/lms-sys/protogen/moduleb\x06proto3"

var file_module_service_module_proto_goTypes = []any{
	(*CreateModuleRequest)(nil),   // 0: lms.modules.CreateModuleRequest
	(*UpdateModuleRequest)(nil),   // 1: lms.modules.UpdateModuleRequest
	(*DeleteModulesRequest)(nil),  // 2: lms.modules.DeleteModulesRequest
	(*emptypb.Empty)(nil),         // 3: google.protobuf.Empty
	(*GetModuleRequest)(nil),      // 4: lms.modules.GetModuleRequest
	(*CreateModuleResponse)(nil),  // 5: lms.modules.CreateModuleResponse
	(*UpdateModuleResponse)(nil),  // 6: lms.modules.UpdateModuleResponse
	(*DeleteModulesResponse)(nil), // 7: lms.modules.DeleteModulesResponse
	(*ListModulesResponse)(nil),   // 8: lms.modules.ListModulesResponse
	(*GetModuleResponse)(nil),     // 9: lms.modules.GetModuleResponse
}
var file_module_service_module_proto_depIdxs = []int32{
	0, // 0: lms.modules.ModuleService.CreateModule:input_type -> lms.modules.CreateModuleRequest
	1, // 1: lms.modules.ModuleService.UpdateModule:input_type -> lms.modules.UpdateModuleRequest
	2, // 2: lms.modules.ModuleService.DeleteModules:input_type -> lms.modules.DeleteModulesRequest
	3, // 3: lms.modules.ModuleService.ListModules:input_type -> google.protobuf.Empty
	4, // 4: lms.modules.ModuleService.GetModule:input_type -> lms.modules.GetModuleRequest
	5, // 5: lms.modules.ModuleService.CreateModule:output_type -> lms.modules.CreateModuleResponse
	6, // 6: lms.modules.ModuleService.UpdateModule:output_type -> lms.modules.UpdateModuleResponse
	7, // 7: lms.modules.ModuleService.DeleteModules:output_type -> lms.modules.DeleteModulesResponse
	8, // 8: lms.modules.ModuleService.ListModules:output_type -> lms.modules.ListModulesResponse
	9, // 9: lms.modules.ModuleService.GetModule:output_type -> lms.modules.GetModuleResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_module_service_module_proto_init() }
func file_module_service_module_proto_init() {
	if File_module_service_module_proto != nil {
		return
	}
	file_module_rpc_create_module_proto_init()
	file_module_rpc_delete_modules_proto_init()
	file_module_rpc_get_module_proto_init()
	file_module_rpc_list_modules_proto_init()
	file_module_rpc_update_module_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_module_service_module_proto_rawDesc), len(file_module_service_module_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_module_service_module_proto_goTypes,
		DependencyIndexes: file_module_service_module_proto_depIdxs,
	}.Build()
	File_module_service_module_proto = out.File
	file_module_service_module_proto_goTypes = nil
	file_module_service_module_proto_depIdxs = nil
}
