// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateNewTenant(ctx context.Context, arg CreateNewTenantParams) (Tenant, error)
	GetTenantByID(ctx context.Context, tenantID pgtype.UUID) (Tenant, error)
	GetTenantByNamespace(ctx context.Context, namespace string) (Tenant, error)
}

var _ Querier = (*Queries)(nil)
