// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: enrollments/rpc_search_enrollments.proto

package enrollment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchEnrollmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentEmail  *string                `protobuf:"bytes,2,opt,name=student_email,json=studentEmail,proto3,oneof" json:"student_email,omitempty"`
	CourseId      *string                `protobuf:"bytes,3,opt,name=course_id,json=courseId,proto3,oneof" json:"course_id,omitempty"`
	CategoryId    *string                `protobuf:"bytes,4,opt,name=category_id,json=categoryId,proto3,oneof" json:"category_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchEnrollmentsRequest) Reset() {
	*x = SearchEnrollmentsRequest{}
	mi := &file_enrollments_rpc_search_enrollments_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchEnrollmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchEnrollmentsRequest) ProtoMessage() {}

func (x *SearchEnrollmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_enrollments_rpc_search_enrollments_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchEnrollmentsRequest.ProtoReflect.Descriptor instead.
func (*SearchEnrollmentsRequest) Descriptor() ([]byte, []int) {
	return file_enrollments_rpc_search_enrollments_proto_rawDescGZIP(), []int{0}
}

func (x *SearchEnrollmentsRequest) GetStudentEmail() string {
	if x != nil && x.StudentEmail != nil {
		return *x.StudentEmail
	}
	return ""
}

func (x *SearchEnrollmentsRequest) GetCourseId() string {
	if x != nil && x.CourseId != nil {
		return *x.CourseId
	}
	return ""
}

func (x *SearchEnrollmentsRequest) GetCategoryId() string {
	if x != nil && x.CategoryId != nil {
		return *x.CategoryId
	}
	return ""
}

type SearchEnrollmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enrollments   []*EnrollmentResponse  `protobuf:"bytes,1,rep,name=enrollments,proto3" json:"enrollments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchEnrollmentsResponse) Reset() {
	*x = SearchEnrollmentsResponse{}
	mi := &file_enrollments_rpc_search_enrollments_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchEnrollmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchEnrollmentsResponse) ProtoMessage() {}

func (x *SearchEnrollmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_enrollments_rpc_search_enrollments_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchEnrollmentsResponse.ProtoReflect.Descriptor instead.
func (*SearchEnrollmentsResponse) Descriptor() ([]byte, []int) {
	return file_enrollments_rpc_search_enrollments_proto_rawDescGZIP(), []int{1}
}

func (x *SearchEnrollmentsResponse) GetEnrollments() []*EnrollmentResponse {
	if x != nil {
		return x.Enrollments
	}
	return nil
}

var File_enrollments_rpc_search_enrollments_proto protoreflect.FileDescriptor

const file_enrollments_rpc_search_enrollments_proto_rawDesc = "" +
	"\n" +
	"(enrollments/rpc_search_enrollments.proto\x12\x0flms.enrollments\x1a\x1cenrollments/enrollment.proto\"\xbc\x01\n" +
	"\x18SearchEnrollmentsRequest\x12(\n" +
	"\rstudent_email\x18\x02 \x01(\tH\x00R\fstudentEmail\x88\x01\x01\x12 \n" +
	"\tcourse_id\x18\x03 \x01(\tH\x01R\bcourseId\x88\x01\x01\x12$\n" +
	"\vcategory_id\x18\x04 \x01(\tH\x02R\n" +
	"categoryId\x88\x01\x01B\x10\n" +
	"\x0e_student_emailB\f\n" +
	"\n" +
	"_course_idB\x0e\n" +
	"\f_category_id\"b\n" +
	"\x19SearchEnrollmentsResponse\x12E\n" +
	"\venrollments\x18\x01 \x03(\v2#.lms.enrollments.EnrollmentResponseR\venrollmentsB@Z>github.com/multi-tenant-cms-golang/lms-sys/protogen/enrollmentb\x06proto3"

var (
	file_enrollments_rpc_search_enrollments_proto_rawDescOnce sync.Once
	file_enrollments_rpc_search_enrollments_proto_rawDescData []byte
)

func file_enrollments_rpc_search_enrollments_proto_rawDescGZIP() []byte {
	file_enrollments_rpc_search_enrollments_proto_rawDescOnce.Do(func() {
		file_enrollments_rpc_search_enrollments_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_enrollments_rpc_search_enrollments_proto_rawDesc), len(file_enrollments_rpc_search_enrollments_proto_rawDesc)))
	})
	return file_enrollments_rpc_search_enrollments_proto_rawDescData
}

var file_enrollments_rpc_search_enrollments_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_enrollments_rpc_search_enrollments_proto_goTypes = []any{
	(*SearchEnrollmentsRequest)(nil),  // 0: lms.enrollments.SearchEnrollmentsRequest
	(*SearchEnrollmentsResponse)(nil), // 1: lms.enrollments.SearchEnrollmentsResponse
	(*EnrollmentResponse)(nil),        // 2: lms.enrollments.EnrollmentResponse
}
var file_enrollments_rpc_search_enrollments_proto_depIdxs = []int32{
	2, // 0: lms.enrollments.SearchEnrollmentsResponse.enrollments:type_name -> lms.enrollments.EnrollmentResponse
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_enrollments_rpc_search_enrollments_proto_init() }
func file_enrollments_rpc_search_enrollments_proto_init() {
	if File_enrollments_rpc_search_enrollments_proto != nil {
		return
	}
	file_enrollments_enrollment_proto_init()
	file_enrollments_rpc_search_enrollments_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_enrollments_rpc_search_enrollments_proto_rawDesc), len(file_enrollments_rpc_search_enrollments_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_enrollments_rpc_search_enrollments_proto_goTypes,
		DependencyIndexes: file_enrollments_rpc_search_enrollments_proto_depIdxs,
		MessageInfos:      file_enrollments_rpc_search_enrollments_proto_msgTypes,
	}.Build()
	File_enrollments_rpc_search_enrollments_proto = out.File
	file_enrollments_rpc_search_enrollments_proto_goTypes = nil
	file_enrollments_rpc_search_enrollments_proto_depIdxs = nil
}
