// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: enrollments/rpc_create_enrollment.proto

package enrollment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateEnrollmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEnrollmentRequest) Reset() {
	*x = CreateEnrollmentRequest{}
	mi := &file_enrollments_rpc_create_enrollment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEnrollmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEnrollmentRequest) ProtoMessage() {}

func (x *CreateEnrollmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_enrollments_rpc_create_enrollment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEnrollmentRequest.ProtoReflect.Descriptor instead.
func (*CreateEnrollmentRequest) Descriptor() ([]byte, []int) {
	return file_enrollments_rpc_create_enrollment_proto_rawDescGZIP(), []int{0}
}

func (x *CreateEnrollmentRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *CreateEnrollmentRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type CreateEnrollmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enrollment    *EnrollmentResponse    `protobuf:"bytes,1,opt,name=enrollment,proto3" json:"enrollment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEnrollmentResponse) Reset() {
	*x = CreateEnrollmentResponse{}
	mi := &file_enrollments_rpc_create_enrollment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEnrollmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEnrollmentResponse) ProtoMessage() {}

func (x *CreateEnrollmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_enrollments_rpc_create_enrollment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEnrollmentResponse.ProtoReflect.Descriptor instead.
func (*CreateEnrollmentResponse) Descriptor() ([]byte, []int) {
	return file_enrollments_rpc_create_enrollment_proto_rawDescGZIP(), []int{1}
}

func (x *CreateEnrollmentResponse) GetEnrollment() *EnrollmentResponse {
	if x != nil {
		return x.Enrollment
	}
	return nil
}

var File_enrollments_rpc_create_enrollment_proto protoreflect.FileDescriptor

const file_enrollments_rpc_create_enrollment_proto_rawDesc = "" +
	"\n" +
	"'enrollments/rpc_create_enrollment.proto\x12\x0flms.enrollments\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cenrollments/enrollment.proto\"U\n" +
	"\x17CreateEnrollmentRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\"_\n" +
	"\x18CreateEnrollmentResponse\x12C\n" +
	"\n" +
	"enrollment\x18\x01 \x01(\v2#.lms.enrollments.EnrollmentResponseR\n" +
	"enrollmentB@Z>github.com/multi-tenant-cms-golang/lms-sys/protogen/enrollmentb\x06proto3"

var (
	file_enrollments_rpc_create_enrollment_proto_rawDescOnce sync.Once
	file_enrollments_rpc_create_enrollment_proto_rawDescData []byte
)

func file_enrollments_rpc_create_enrollment_proto_rawDescGZIP() []byte {
	file_enrollments_rpc_create_enrollment_proto_rawDescOnce.Do(func() {
		file_enrollments_rpc_create_enrollment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_enrollments_rpc_create_enrollment_proto_rawDesc), len(file_enrollments_rpc_create_enrollment_proto_rawDesc)))
	})
	return file_enrollments_rpc_create_enrollment_proto_rawDescData
}

var file_enrollments_rpc_create_enrollment_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_enrollments_rpc_create_enrollment_proto_goTypes = []any{
	(*CreateEnrollmentRequest)(nil),  // 0: lms.enrollments.CreateEnrollmentRequest
	(*CreateEnrollmentResponse)(nil), // 1: lms.enrollments.CreateEnrollmentResponse
	(*EnrollmentResponse)(nil),       // 2: lms.enrollments.EnrollmentResponse
}
var file_enrollments_rpc_create_enrollment_proto_depIdxs = []int32{
	2, // 0: lms.enrollments.CreateEnrollmentResponse.enrollment:type_name -> lms.enrollments.EnrollmentResponse
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_enrollments_rpc_create_enrollment_proto_init() }
func file_enrollments_rpc_create_enrollment_proto_init() {
	if File_enrollments_rpc_create_enrollment_proto != nil {
		return
	}
	file_enrollments_enrollment_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_enrollments_rpc_create_enrollment_proto_rawDesc), len(file_enrollments_rpc_create_enrollment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_enrollments_rpc_create_enrollment_proto_goTypes,
		DependencyIndexes: file_enrollments_rpc_create_enrollment_proto_depIdxs,
		MessageInfos:      file_enrollments_rpc_create_enrollment_proto_msgTypes,
	}.Build()
	File_enrollments_rpc_create_enrollment_proto = out.File
	file_enrollments_rpc_create_enrollment_proto_goTypes = nil
	file_enrollments_rpc_create_enrollment_proto_depIdxs = nil
}
