/*
assignment/assignment.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CourseCreateCourseRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CourseCreateCourseRequest{}

// CourseCreateCourseRequest struct for CourseCreateCourseRequest
type CourseCreateCourseRequest struct {
	CourseTitle *string `json:"courseTitle,omitempty"`
}

// NewCourseCreateCourseRequest instantiates a new CourseCreateCourseRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCourseCreateCourseRequest() *CourseCreateCourseRequest {
	this := CourseCreateCourseRequest{}
	return &this
}

// NewCourseCreateCourseRequestWithDefaults instantiates a new CourseCreateCourseRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCourseCreateCourseRequestWithDefaults() *CourseCreateCourseRequest {
	this := CourseCreateCourseRequest{}
	return &this
}

// GetCourseTitle returns the CourseTitle field value if set, zero value otherwise.
func (o *CourseCreateCourseRequest) GetCourseTitle() string {
	if o == nil || IsNil(o.CourseTitle) {
		var ret string
		return ret
	}
	return *o.CourseTitle
}

// GetCourseTitleOk returns a tuple with the CourseTitle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CourseCreateCourseRequest) GetCourseTitleOk() (*string, bool) {
	if o == nil || IsNil(o.CourseTitle) {
		return nil, false
	}
	return o.CourseTitle, true
}

// HasCourseTitle returns a boolean if a field has been set.
func (o *CourseCreateCourseRequest) HasCourseTitle() bool {
	if o != nil && !IsNil(o.CourseTitle) {
		return true
	}

	return false
}

// SetCourseTitle gets a reference to the given string and assigns it to the CourseTitle field.
func (o *CourseCreateCourseRequest) SetCourseTitle(v string) {
	o.CourseTitle = &v
}

func (o CourseCreateCourseRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CourseCreateCourseRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CourseTitle) {
		toSerialize["courseTitle"] = o.CourseTitle
	}
	return toSerialize, nil
}

type NullableCourseCreateCourseRequest struct {
	value *CourseCreateCourseRequest
	isSet bool
}

func (v NullableCourseCreateCourseRequest) Get() *CourseCreateCourseRequest {
	return v.value
}

func (v *NullableCourseCreateCourseRequest) Set(val *CourseCreateCourseRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCourseCreateCourseRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCourseCreateCourseRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCourseCreateCourseRequest(val *CourseCreateCourseRequest) *NullableCourseCreateCourseRequest {
	return &NullableCourseCreateCourseRequest{value: val, isSet: true}
}

func (v NullableCourseCreateCourseRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCourseCreateCourseRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


