/*
assignment/assignment.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AssignmentCreateAssignmentRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AssignmentCreateAssignmentRequest{}

// AssignmentCreateAssignmentRequest struct for AssignmentCreateAssignmentRequest
type AssignmentCreateAssignmentRequest struct {
	CourseId *string `json:"courseId,omitempty"`
	Title *string `json:"title,omitempty"`
	Instructions *string `json:"instructions,omitempty"`
}

// NewAssignmentCreateAssignmentRequest instantiates a new AssignmentCreateAssignmentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssignmentCreateAssignmentRequest() *AssignmentCreateAssignmentRequest {
	this := AssignmentCreateAssignmentRequest{}
	return &this
}

// NewAssignmentCreateAssignmentRequestWithDefaults instantiates a new AssignmentCreateAssignmentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssignmentCreateAssignmentRequestWithDefaults() *AssignmentCreateAssignmentRequest {
	this := AssignmentCreateAssignmentRequest{}
	return &this
}

// GetCourseId returns the CourseId field value if set, zero value otherwise.
func (o *AssignmentCreateAssignmentRequest) GetCourseId() string {
	if o == nil || IsNil(o.CourseId) {
		var ret string
		return ret
	}
	return *o.CourseId
}

// GetCourseIdOk returns a tuple with the CourseId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssignmentCreateAssignmentRequest) GetCourseIdOk() (*string, bool) {
	if o == nil || IsNil(o.CourseId) {
		return nil, false
	}
	return o.CourseId, true
}

// HasCourseId returns a boolean if a field has been set.
func (o *AssignmentCreateAssignmentRequest) HasCourseId() bool {
	if o != nil && !IsNil(o.CourseId) {
		return true
	}

	return false
}

// SetCourseId gets a reference to the given string and assigns it to the CourseId field.
func (o *AssignmentCreateAssignmentRequest) SetCourseId(v string) {
	o.CourseId = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *AssignmentCreateAssignmentRequest) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssignmentCreateAssignmentRequest) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *AssignmentCreateAssignmentRequest) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *AssignmentCreateAssignmentRequest) SetTitle(v string) {
	o.Title = &v
}

// GetInstructions returns the Instructions field value if set, zero value otherwise.
func (o *AssignmentCreateAssignmentRequest) GetInstructions() string {
	if o == nil || IsNil(o.Instructions) {
		var ret string
		return ret
	}
	return *o.Instructions
}

// GetInstructionsOk returns a tuple with the Instructions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssignmentCreateAssignmentRequest) GetInstructionsOk() (*string, bool) {
	if o == nil || IsNil(o.Instructions) {
		return nil, false
	}
	return o.Instructions, true
}

// HasInstructions returns a boolean if a field has been set.
func (o *AssignmentCreateAssignmentRequest) HasInstructions() bool {
	if o != nil && !IsNil(o.Instructions) {
		return true
	}

	return false
}

// SetInstructions gets a reference to the given string and assigns it to the Instructions field.
func (o *AssignmentCreateAssignmentRequest) SetInstructions(v string) {
	o.Instructions = &v
}

func (o AssignmentCreateAssignmentRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AssignmentCreateAssignmentRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CourseId) {
		toSerialize["courseId"] = o.CourseId
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.Instructions) {
		toSerialize["instructions"] = o.Instructions
	}
	return toSerialize, nil
}

type NullableAssignmentCreateAssignmentRequest struct {
	value *AssignmentCreateAssignmentRequest
	isSet bool
}

func (v NullableAssignmentCreateAssignmentRequest) Get() *AssignmentCreateAssignmentRequest {
	return v.value
}

func (v *NullableAssignmentCreateAssignmentRequest) Set(val *AssignmentCreateAssignmentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAssignmentCreateAssignmentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAssignmentCreateAssignmentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssignmentCreateAssignmentRequest(val *AssignmentCreateAssignmentRequest) *NullableAssignmentCreateAssignmentRequest {
	return &NullableAssignmentCreateAssignmentRequest{value: val, isSet: true}
}

func (v NullableAssignmentCreateAssignmentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssignmentCreateAssignmentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


