// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: enrollment/enrollment.proto

package enrollment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Enrollment struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EnrollmentId   string                 `protobuf:"bytes,1,opt,name=enrollment_id,json=enrollmentId,proto3" json:"enrollment_id,omitempty"`
	StudentId      string                 `protobuf:"bytes,2,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	CourseId       string                 `protobuf:"bytes,3,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	EnrollmentDate *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=enrollment_date,json=enrollmentDate,proto3" json:"enrollment_date,omitempty"`
	Progress       float64                `protobuf:"fixed64,5,opt,name=progress,proto3" json:"progress,omitempty"`
	Status         string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	DueDate        *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Enrollment) Reset() {
	*x = Enrollment{}
	mi := &file_enrollment_enrollment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Enrollment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Enrollment) ProtoMessage() {}

func (x *Enrollment) ProtoReflect() protoreflect.Message {
	mi := &file_enrollment_enrollment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Enrollment.ProtoReflect.Descriptor instead.
func (*Enrollment) Descriptor() ([]byte, []int) {
	return file_enrollment_enrollment_proto_rawDescGZIP(), []int{0}
}

func (x *Enrollment) GetEnrollmentId() string {
	if x != nil {
		return x.EnrollmentId
	}
	return ""
}

func (x *Enrollment) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *Enrollment) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *Enrollment) GetEnrollmentDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EnrollmentDate
	}
	return nil
}

func (x *Enrollment) GetProgress() float64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *Enrollment) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Enrollment) GetDueDate() *timestamppb.Timestamp {
	if x != nil {
		return x.DueDate
	}
	return nil
}

func (x *Enrollment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Enrollment) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_enrollment_enrollment_proto protoreflect.FileDescriptor

const file_enrollment_enrollment_proto_rawDesc = "" +
	"\n" +
	"\x1benrollment/enrollment.proto\x12\x0elms.enrollment\x1a\x1fgoogle/protobuf/timestamp.proto\"\x93\x03\n" +
	"\n" +
	"Enrollment\x12#\n" +
	"\renrollment_id\x18\x01 \x01(\tR\fenrollmentId\x12\x1d\n" +
	"\n" +
	"student_id\x18\x02 \x01(\tR\tstudentId\x12\x1b\n" +
	"\tcourse_id\x18\x03 \x01(\tR\bcourseId\x12C\n" +
	"\x0fenrollment_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x0eenrollmentDate\x12\x1a\n" +
	"\bprogress\x18\x05 \x01(\x01R\bprogress\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x125\n" +
	"\bdue_date\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\adueDate\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB@Z>github.com/multi-tenant-cms-golang/lms-sys/protogen/enrollmentb\x06proto3"

var (
	file_enrollment_enrollment_proto_rawDescOnce sync.Once
	file_enrollment_enrollment_proto_rawDescData []byte
)

func file_enrollment_enrollment_proto_rawDescGZIP() []byte {
	file_enrollment_enrollment_proto_rawDescOnce.Do(func() {
		file_enrollment_enrollment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_enrollment_enrollment_proto_rawDesc), len(file_enrollment_enrollment_proto_rawDesc)))
	})
	return file_enrollment_enrollment_proto_rawDescData
}

var file_enrollment_enrollment_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_enrollment_enrollment_proto_goTypes = []any{
	(*Enrollment)(nil),            // 0: lms.enrollment.Enrollment
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_enrollment_enrollment_proto_depIdxs = []int32{
	1, // 0: lms.enrollment.Enrollment.enrollment_date:type_name -> google.protobuf.Timestamp
	1, // 1: lms.enrollment.Enrollment.due_date:type_name -> google.protobuf.Timestamp
	1, // 2: lms.enrollment.Enrollment.created_at:type_name -> google.protobuf.Timestamp
	1, // 3: lms.enrollment.Enrollment.updated_at:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_enrollment_enrollment_proto_init() }
func file_enrollment_enrollment_proto_init() {
	if File_enrollment_enrollment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_enrollment_enrollment_proto_rawDesc), len(file_enrollment_enrollment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_enrollment_enrollment_proto_goTypes,
		DependencyIndexes: file_enrollment_enrollment_proto_depIdxs,
		MessageInfos:      file_enrollment_enrollment_proto_msgTypes,
	}.Build()
	File_enrollment_enrollment_proto = out.File
	file_enrollment_enrollment_proto_goTypes = nil
	file_enrollment_enrollment_proto_depIdxs = nil
}
