// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: assignment/assignment.proto

package assignment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Assignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssignmentId  string                 `protobuf:"bytes,1,opt,name=assignment_id,json=assignmentId,proto3" json:"assignment_id,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Instruction   string                 `protobuf:"bytes,4,opt,name=instruction,proto3" json:"instruction,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Assignment) Reset() {
	*x = Assignment{}
	mi := &file_assignment_assignment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Assignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Assignment) ProtoMessage() {}

func (x *Assignment) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_assignment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Assignment.ProtoReflect.Descriptor instead.
func (*Assignment) Descriptor() ([]byte, []int) {
	return file_assignment_assignment_proto_rawDescGZIP(), []int{0}
}

func (x *Assignment) GetAssignmentId() string {
	if x != nil {
		return x.AssignmentId
	}
	return ""
}

func (x *Assignment) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *Assignment) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Assignment) GetInstruction() string {
	if x != nil {
		return x.Instruction
	}
	return ""
}

func (x *Assignment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Assignment) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_assignment_assignment_proto protoreflect.FileDescriptor

const file_assignment_assignment_proto_rawDesc = "" +
	"\n" +
	"\x1bassignment/assignment.proto\x12\x0elms.assignment\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfc\x01\n" +
	"\n" +
	"Assignment\x12#\n" +
	"\rassignment_id\x18\x01 \x01(\tR\fassignmentId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vinstruction\x18\x04 \x01(\tR\vinstruction\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB@Z>github.com/multi-tenant-cms-golang/lms-sys/protogen/assignmentb\x06proto3"

var (
	file_assignment_assignment_proto_rawDescOnce sync.Once
	file_assignment_assignment_proto_rawDescData []byte
)

func file_assignment_assignment_proto_rawDescGZIP() []byte {
	file_assignment_assignment_proto_rawDescOnce.Do(func() {
		file_assignment_assignment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_assignment_assignment_proto_rawDesc), len(file_assignment_assignment_proto_rawDesc)))
	})
	return file_assignment_assignment_proto_rawDescData
}

var file_assignment_assignment_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_assignment_assignment_proto_goTypes = []any{
	(*Assignment)(nil),            // 0: lms.assignment.Assignment
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_assignment_assignment_proto_depIdxs = []int32{
	1, // 0: lms.assignment.Assignment.created_at:type_name -> google.protobuf.Timestamp
	1, // 1: lms.assignment.Assignment.updated_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_assignment_assignment_proto_init() }
func file_assignment_assignment_proto_init() {
	if File_assignment_assignment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_assignment_assignment_proto_rawDesc), len(file_assignment_assignment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_assignment_assignment_proto_goTypes,
		DependencyIndexes: file_assignment_assignment_proto_depIdxs,
		MessageInfos:      file_assignment_assignment_proto_msgTypes,
	}.Build()
	File_assignment_assignment_proto = out.File
	file_assignment_assignment_proto_goTypes = nil
	file_assignment_assignment_proto_depIdxs = nil
}
