// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: course/rpc_course_create.proto

package course

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseTitle   string                 `protobuf:"bytes,1,opt,name=course_title,json=courseTitle,proto3" json:"course_title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCourseRequest) Reset() {
	*x = CreateCourseRequest{}
	mi := &file_course_rpc_course_create_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCourseRequest) ProtoMessage() {}

func (x *CreateCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_rpc_course_create_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCourseRequest.ProtoReflect.Descriptor instead.
func (*CreateCourseRequest) Descriptor() ([]byte, []int) {
	return file_course_rpc_course_create_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCourseRequest) GetCourseTitle() string {
	if x != nil {
		return x.CourseTitle
	}
	return ""
}

type CreateCourseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseCreated *Course                `protobuf:"bytes,1,opt,name=course_created,json=courseCreated,proto3" json:"course_created,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCourseResponse) Reset() {
	*x = CreateCourseResponse{}
	mi := &file_course_rpc_course_create_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCourseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCourseResponse) ProtoMessage() {}

func (x *CreateCourseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_rpc_course_create_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCourseResponse.ProtoReflect.Descriptor instead.
func (*CreateCourseResponse) Descriptor() ([]byte, []int) {
	return file_course_rpc_course_create_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCourseResponse) GetCourseCreated() *Course {
	if x != nil {
		return x.CourseCreated
	}
	return nil
}

var File_course_rpc_course_create_proto protoreflect.FileDescriptor

const file_course_rpc_course_create_proto_rawDesc = "" +
	"\n" +
	"\x1ecourse/rpc_course_create.proto\x12\n" +
	"lms.course\x1a\x13course/course.proto\"8\n" +
	"\x13CreateCourseRequest\x12!\n" +
	"\fcourse_title\x18\x01 \x01(\tR\vcourseTitle\"Q\n" +
	"\x14CreateCourseResponse\x129\n" +
	"\x0ecourse_created\x18\x01 \x01(\v2\x12.lms.course.CourseR\rcourseCreatedB<Z:github.com/multi-tenant-cms-golang/lms-sys/protogen/courseb\x06proto3"

var (
	file_course_rpc_course_create_proto_rawDescOnce sync.Once
	file_course_rpc_course_create_proto_rawDescData []byte
)

func file_course_rpc_course_create_proto_rawDescGZIP() []byte {
	file_course_rpc_course_create_proto_rawDescOnce.Do(func() {
		file_course_rpc_course_create_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_course_rpc_course_create_proto_rawDesc), len(file_course_rpc_course_create_proto_rawDesc)))
	})
	return file_course_rpc_course_create_proto_rawDescData
}

var file_course_rpc_course_create_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_course_rpc_course_create_proto_goTypes = []any{
	(*CreateCourseRequest)(nil),  // 0: lms.course.CreateCourseRequest
	(*CreateCourseResponse)(nil), // 1: lms.course.CreateCourseResponse
	(*Course)(nil),               // 2: lms.course.Course
}
var file_course_rpc_course_create_proto_depIdxs = []int32{
	2, // 0: lms.course.CreateCourseResponse.course_created:type_name -> lms.course.Course
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_course_rpc_course_create_proto_init() }
func file_course_rpc_course_create_proto_init() {
	if File_course_rpc_course_create_proto != nil {
		return
	}
	file_course_course_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_course_rpc_course_create_proto_rawDesc), len(file_course_rpc_course_create_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_course_rpc_course_create_proto_goTypes,
		DependencyIndexes: file_course_rpc_course_create_proto_depIdxs,
		MessageInfos:      file_course_rpc_course_create_proto_msgTypes,
	}.Build()
	File_course_rpc_course_create_proto = out.File
	file_course_rpc_course_create_proto_goTypes = nil
	file_course_rpc_course_create_proto_depIdxs = nil
}
