// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: files/service.file.proto

package files

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileStatusResponse_Status int32

const (
	FileStatusResponse_STATUS_UNSPECIFIED FileStatusResponse_Status = 0
	FileStatusResponse_QUEUED             FileStatusResponse_Status = 1
	FileStatusResponse_PROCESSING         FileStatusResponse_Status = 2
	FileStatusResponse_COMPLETED          FileStatusResponse_Status = 3
	FileStatusResponse_FAILED             FileStatusResponse_Status = 4
)

// Enum value maps for FileStatusResponse_Status.
var (
	FileStatusResponse_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "QUEUED",
		2: "PROCESSING",
		3: "COMPLETED",
		4: "FAILED",
	}
	FileStatusResponse_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"QUEUED":             1,
		"PROCESSING":         2,
		"COMPLETED":          3,
		"FAILED":             4,
	}
)

func (x FileStatusResponse_Status) Enum() *FileStatusResponse_Status {
	p := new(FileStatusResponse_Status)
	*p = x
	return p
}

func (x FileStatusResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileStatusResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_files_service_file_proto_enumTypes[0].Descriptor()
}

func (FileStatusResponse_Status) Type() protoreflect.EnumType {
	return &file_files_service_file_proto_enumTypes[0]
}

func (x FileStatusResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileStatusResponse_Status.Descriptor instead.
func (FileStatusResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_files_service_file_proto_rawDescGZIP(), []int{4, 0}
}

type UploadFileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*UploadFileRequest_Metadata
	//	*UploadFileRequest_Chunk
	Data          isUploadFileRequest_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileRequest) Reset() {
	*x = UploadFileRequest{}
	mi := &file_files_service_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileRequest) ProtoMessage() {}

func (x *UploadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_files_service_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileRequest.ProtoReflect.Descriptor instead.
func (*UploadFileRequest) Descriptor() ([]byte, []int) {
	return file_files_service_file_proto_rawDescGZIP(), []int{0}
}

func (x *UploadFileRequest) GetData() isUploadFileRequest_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadFileRequest) GetMetadata() *FileMetadata {
	if x != nil {
		if x, ok := x.Data.(*UploadFileRequest_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *UploadFileRequest) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Data.(*UploadFileRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isUploadFileRequest_Data interface {
	isUploadFileRequest_Data()
}

type UploadFileRequest_Metadata struct {
	Metadata *FileMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type UploadFileRequest_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*UploadFileRequest_Metadata) isUploadFileRequest_Data() {}

func (*UploadFileRequest_Chunk) isUploadFileRequest_Data() {}

type FileMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileMetadata) Reset() {
	*x = FileMetadata{}
	mi := &file_files_service_file_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMetadata) ProtoMessage() {}

func (x *FileMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_files_service_file_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMetadata.ProtoReflect.Descriptor instead.
func (*FileMetadata) Descriptor() ([]byte, []int) {
	return file_files_service_file_proto_rawDescGZIP(), []int{1}
}

func (x *FileMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileMetadata) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FileMetadata) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type UploadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileResponse) Reset() {
	*x = UploadFileResponse{}
	mi := &file_files_service_file_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileResponse) ProtoMessage() {}

func (x *UploadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_files_service_file_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileResponse.ProtoReflect.Descriptor instead.
func (*UploadFileResponse) Descriptor() ([]byte, []int) {
	return file_files_service_file_proto_rawDescGZIP(), []int{2}
}

func (x *UploadFileResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetFileStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileStatusRequest) Reset() {
	*x = GetFileStatusRequest{}
	mi := &file_files_service_file_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileStatusRequest) ProtoMessage() {}

func (x *GetFileStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_files_service_file_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileStatusRequest.ProtoReflect.Descriptor instead.
func (*GetFileStatusRequest) Descriptor() ([]byte, []int) {
	return file_files_service_file_proto_rawDescGZIP(), []int{3}
}

func (x *GetFileStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type FileStatusResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Id            string                    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        FileStatusResponse_Status `protobuf:"varint,2,opt,name=status,proto3,enum=lms.files.FileStatusResponse_Status" json:"status,omitempty"`
	IpfsCid       string                    `protobuf:"bytes,3,opt,name=ipfs_cid,json=ipfsCid,proto3" json:"ipfs_cid,omitempty"`
	ErrorMessage  string                    `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	QueuedAt      *timestamppb.Timestamp    `protobuf:"bytes,5,opt,name=queued_at,json=queuedAt,proto3" json:"queued_at,omitempty"`
	StartedAt     *timestamppb.Timestamp    `protobuf:"bytes,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp    `protobuf:"bytes,7,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileStatusResponse) Reset() {
	*x = FileStatusResponse{}
	mi := &file_files_service_file_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileStatusResponse) ProtoMessage() {}

func (x *FileStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_files_service_file_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileStatusResponse.ProtoReflect.Descriptor instead.
func (*FileStatusResponse) Descriptor() ([]byte, []int) {
	return file_files_service_file_proto_rawDescGZIP(), []int{4}
}

func (x *FileStatusResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FileStatusResponse) GetStatus() FileStatusResponse_Status {
	if x != nil {
		return x.Status
	}
	return FileStatusResponse_STATUS_UNSPECIFIED
}

func (x *FileStatusResponse) GetIpfsCid() string {
	if x != nil {
		return x.IpfsCid
	}
	return ""
}

func (x *FileStatusResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *FileStatusResponse) GetQueuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.QueuedAt
	}
	return nil
}

func (x *FileStatusResponse) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *FileStatusResponse) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

var File_files_service_file_proto protoreflect.FileDescriptor

const file_files_service_file_proto_rawDesc = "" +
	"\n" +
	"\x18files/service.file.proto\x12\tlms.files\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"j\n" +
	"\x11UploadFileRequest\x125\n" +
	"\bmetadata\x18\x01 \x01(\v2\x17.lms.files.FileMetadataH\x00R\bmetadata\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunkB\x06\n" +
	"\x04data\"\xae\x01\n" +
	"\fFileMetadata\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12;\n" +
	"\x06labels\x18\x03 \x03(\v2#.lms.files.FileMetadata.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"$\n" +
	"\x12UploadFileResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"&\n" +
	"\x14GetFileStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xae\x03\n" +
	"\x12FileStatusResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12<\n" +
	"\x06status\x18\x02 \x01(\x0e2$.lms.files.FileStatusResponse.StatusR\x06status\x12\x19\n" +
	"\bipfs_cid\x18\x03 \x01(\tR\aipfsCid\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x127\n" +
	"\tqueued_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bqueuedAt\x129\n" +
	"\n" +
	"started_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"W\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06QUEUED\x10\x01\x12\x0e\n" +
	"\n" +
	"PROCESSING\x10\x02\x12\r\n" +
	"\tCOMPLETED\x10\x03\x12\n" +
	"\n" +
	"\x06FAILED\x10\x042\xe0\x01\n" +
	"\vFileService\x12a\n" +
	"\n" +
	"UploadFile\x12\x1c.lms.files.UploadFileRequest\x1a\x1d.lms.files.UploadFileResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/files(\x01\x12n\n" +
	"\rGetFileStatus\x12\x1f.lms.files.GetFileStatusRequest\x1a\x1d.lms.files.FileStatusResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/files/{id}/statusB<Z:github.com/multi-tenants-cms-golang/lms-sys/protogen/filesb\x06proto3"

var (
	file_files_service_file_proto_rawDescOnce sync.Once
	file_files_service_file_proto_rawDescData []byte
)

func file_files_service_file_proto_rawDescGZIP() []byte {
	file_files_service_file_proto_rawDescOnce.Do(func() {
		file_files_service_file_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_files_service_file_proto_rawDesc), len(file_files_service_file_proto_rawDesc)))
	})
	return file_files_service_file_proto_rawDescData
}

var file_files_service_file_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_files_service_file_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_files_service_file_proto_goTypes = []any{
	(FileStatusResponse_Status)(0), // 0: lms.files.FileStatusResponse.Status
	(*UploadFileRequest)(nil),      // 1: lms.files.UploadFileRequest
	(*FileMetadata)(nil),           // 2: lms.files.FileMetadata
	(*UploadFileResponse)(nil),     // 3: lms.files.UploadFileResponse
	(*GetFileStatusRequest)(nil),   // 4: lms.files.GetFileStatusRequest
	(*FileStatusResponse)(nil),     // 5: lms.files.FileStatusResponse
	nil,                            // 6: lms.files.FileMetadata.LabelsEntry
	(*timestamppb.Timestamp)(nil),  // 7: google.protobuf.Timestamp
}
var file_files_service_file_proto_depIdxs = []int32{
	2, // 0: lms.files.UploadFileRequest.metadata:type_name -> lms.files.FileMetadata
	6, // 1: lms.files.FileMetadata.labels:type_name -> lms.files.FileMetadata.LabelsEntry
	0, // 2: lms.files.FileStatusResponse.status:type_name -> lms.files.FileStatusResponse.Status
	7, // 3: lms.files.FileStatusResponse.queued_at:type_name -> google.protobuf.Timestamp
	7, // 4: lms.files.FileStatusResponse.started_at:type_name -> google.protobuf.Timestamp
	7, // 5: lms.files.FileStatusResponse.completed_at:type_name -> google.protobuf.Timestamp
	1, // 6: lms.files.FileService.UploadFile:input_type -> lms.files.UploadFileRequest
	4, // 7: lms.files.FileService.GetFileStatus:input_type -> lms.files.GetFileStatusRequest
	3, // 8: lms.files.FileService.UploadFile:output_type -> lms.files.UploadFileResponse
	5, // 9: lms.files.FileService.GetFileStatus:output_type -> lms.files.FileStatusResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_files_service_file_proto_init() }
func file_files_service_file_proto_init() {
	if File_files_service_file_proto != nil {
		return
	}
	file_files_service_file_proto_msgTypes[0].OneofWrappers = []any{
		(*UploadFileRequest_Metadata)(nil),
		(*UploadFileRequest_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_files_service_file_proto_rawDesc), len(file_files_service_file_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_files_service_file_proto_goTypes,
		DependencyIndexes: file_files_service_file_proto_depIdxs,
		EnumInfos:         file_files_service_file_proto_enumTypes,
		MessageInfos:      file_files_service_file_proto_msgTypes,
	}.Build()
	File_files_service_file_proto = out.File
	file_files_service_file_proto_goTypes = nil
	file_files_service_file_proto_depIdxs = nil
}
