-- Drop tables in reverse dependency order
DROP TABLE IF EXISTS Report;
DROP TABLE IF EXISTS Review;
DROP TABLE IF EXISTS Submission;
DROP TABLE IF EXISTS Assignment;
DROP TABLE IF EXISTS Lesson;
DROP TABLE IF EXISTS Student_Quiz;
DROP TABLE IF EXISTS Quiz;
DROP TABLE IF EXISTS Module;
DROP TABLE IF EXISTS Rating;
DROP TABLE IF EXISTS Certificate;
DROP TABLE IF EXISTS enrollment;
DROP TABLE IF EXISTS namespace_consumer;
DROP TABLE IF EXISTS Course;
DROP TABLE IF EXISTS Course_Category;
DROP TABLE IF EXISTS Tenants_Members;
DROP TABLE IF EXISTS LMS_USER;
DROP TABLE IF EXISTS Tenants;
DROP TABLE IF EXISTS LMS_USER_Role;

-- Drop custom types
DROP TYPE IF EXISTS course_status;
DROP TYPE IF EXISTS material_type;
DROP TYPE IF EXISTS enrollment_type;
DROP TYPE IF EXISTS system_type;
DROP TYPE IF EXISTS lms_role_type;