// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repo

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	CreateModule(ctx context.Context, arg CreateModuleParams) (Module, error)
	CreateNewCourse(ctx context.Context, courseTitle string) (Course, error)
	CreateNewTenant(ctx context.Context, arg CreateNewTenantParams) (Tenant, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (LmsUser, error)
	DeleteAssociatedLessons(ctx context.Context, moduleID uuid.UUID) error
	DeleteAssociatedQuizzes(ctx context.Context, moduleID uuid.UUID) error
	DeleteModule(ctx context.Context, moduleID uuid.UUID) error
	DeleteModules(ctx context.Context, dollar_1 []uuid.UUID) error
	DeleteUser(ctx context.Context, lmsUserID uuid.UUID) error
	GetAllCourse(ctx context.Context) ([]Course, error)
	GetModuleByID(ctx context.Context, moduleID uuid.UUID) (Module, error)
	GetTenantByID(ctx context.Context, tenantID uuid.UUID) (Tenant, error)
	GetTenantByNamespace(ctx context.Context, namespace string) (Tenant, error)
	GetUser(ctx context.Context, lmsUserID uuid.UUID) (LmsUser, error)
	GetUserByEmail(ctx context.Context, lmsUserEmail string) (LmsUser, error)
	GetUsersByRole(ctx context.Context, lmsRoleID uuid.UUID) ([]LmsUser, error)
	GetUsersByTenant(ctx context.Context, tenantID uuid.NullUUID) ([]LmsUser, error)
	ListModules(ctx context.Context) ([]Module, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]LmsUser, error)
	ModuleHasAssociations(ctx context.Context, moduleID uuid.UUID) (sql.NullBool, error)
	UpdateModuleByID(ctx context.Context, arg UpdateModuleByIDParams) (Module, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (LmsUser, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
