// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repo

import (
	"context"
)

type Querier interface {
	RegisterLMSUser(ctx context.Context, arg RegisterLMSUserParams) (RegisterLMSUserRow, error)
	UpdateEmailVerification(ctx context.Context, lmsUserEmail string) error
}

var _ Querier = (*Queries)(nil)
