import "./lms_user_role.tsp";
import "./tenants.tsp";
import "./lms_user.tsp";
import "./tenants_members.tsp";
import "./course_category.tsp";
import "./course.tsp";
import "./namespace_consumer.tsp";
import "./enrollment.tsp";
import "./certificate.tsp";
import "./rating.tsp";
import "./module.tsp";
import "./quiz.tsp";
import "./student_quiz.tsp";
import "./lesson.tsp";
import "./assignment.tsp";
import "./submission.tsp";
import "./review.tsp";
import "./report.tsp";

@service({
  title: "LMS Combined Service",
})
namespace LMS {
// Expose all imported namespaces here if needed

}
