// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: enrollment.sql

package repo

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createEnrollment = `-- name: CreateEnrollment :one
INSERT INTO Enrollment (
    student_id,   
    course_id,
    status,
    due_date,
    updated_at
)
SELECT
    $1,
    $2,
    $3,
    $4,
    CURRENT_TIMESTAMP
FROM Course c
WHERE c.course_id = $2 AND c.status = 'Active'
RETURNING enrollment_id
`

type CreateEnrollmentParams struct {
	StudentID uuid.UUID        `json:"student_id"`
	CourseID  uuid.UUID        `json:"course_id"`
	Status    EnrollmentType   `json:"status"`
	DueDate   pgtype.Timestamp `json:"due_date"`
}

func (q *Queries) CreateEnrollment(ctx context.Context, arg CreateEnrollmentParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createEnrollment,
		arg.StudentID,
		arg.CourseID,
		arg.Status,
		arg.DueDate,
	)
	var enrollment_id uuid.UUID
	err := row.Scan(&enrollment_id)
	return enrollment_id, err
}

const deleteEnrollmentsByID = `-- name: DeleteEnrollmentsByID :exec
DELETE FROM Enrollment
WHERE enrollment_id = $1
`

func (q *Queries) DeleteEnrollmentsByID(ctx context.Context, enrollmentID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEnrollmentsByID, enrollmentID)
	return err
}

const getEnrollmentByIDAndTenant = `-- name: GetEnrollmentByIDAndTenant :one
SELECT enrollment_id, enrollment_date, progress, status, due_date, created_at, student_id, student_name, student_email, course_id, course_title, course_category, owned_by, instructor_id, category_id, category_name, namespace, tenant_id FROM enrollment_details
WHERE namespace = $1 AND enrollment_id = $2
`

type GetEnrollmentByIDAndTenantParams struct {
	Namespace    string    `json:"namespace"`
	EnrollmentID uuid.UUID `json:"enrollment_id"`
}

func (q *Queries) GetEnrollmentByIDAndTenant(ctx context.Context, arg GetEnrollmentByIDAndTenantParams) (EnrollmentDetails, error) {
	row := q.db.QueryRow(ctx, getEnrollmentByIDAndTenant, arg.Namespace, arg.EnrollmentID)
	var i EnrollmentDetails
	err := row.Scan(
		&i.EnrollmentID,
		&i.EnrollmentDate,
		&i.Progress,
		&i.Status,
		&i.DueDate,
		&i.CreatedAt,
		&i.StudentID,
		&i.StudentName,
		&i.StudentEmail,
		&i.CourseID,
		&i.CourseTitle,
		&i.CourseCategory,
		&i.OwnedBy,
		&i.InstructorID,
		&i.CategoryID,
		&i.CategoryName,
		&i.Namespace,
		&i.TenantID,
	)
	return i, err
}

const isEnrollmentExist = `-- name: IsEnrollmentExist :one
SELECT EXISTS (
    SELECT 1
    FROM Enrollment e
    WHERE student_id = $1 AND course_id = $2
) as exists
`

type IsEnrollmentExistParams struct {
	StudentID uuid.UUID `json:"student_id"`
	CourseID  uuid.UUID `json:"course_id"`
}

func (q *Queries) IsEnrollmentExist(ctx context.Context, arg IsEnrollmentExistParams) (bool, error) {
	row := q.db.QueryRow(ctx, isEnrollmentExist, arg.StudentID, arg.CourseID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isEnrollmentOwnedByTenant = `-- name: IsEnrollmentOwnedByTenant :one
SELECT EXISTS (
    SELECT 1
    From Enrollment e
    JOIN Course c ON c.course_id = e.course_id
    JOIN Tenants t ON t.tenant_id = c.owned_by
    WHERE t.namespace = $1 AND e.enrollment_id = $2
) as is_owned
`

type IsEnrollmentOwnedByTenantParams struct {
	Namespace    string    `json:"namespace"`
	EnrollmentID uuid.UUID `json:"enrollment_id"`
}

func (q *Queries) IsEnrollmentOwnedByTenant(ctx context.Context, arg IsEnrollmentOwnedByTenantParams) (bool, error) {
	row := q.db.QueryRow(ctx, isEnrollmentOwnedByTenant, arg.Namespace, arg.EnrollmentID)
	var is_owned bool
	err := row.Scan(&is_owned)
	return is_owned, err
}

const isUserInRole = `-- name: IsUserInRole :one
SELECT EXISTS (
    SELECT 1 
    FROM user_role_details
    WHERE namespace = $1 
        AND lms_user_id = $2 
        AND lms_role_name = $3
        AND tenant_is_active = true
        AND role_map_is_active = true
) as in_role
`

type IsUserInRoleParams struct {
	Namespace   string      `json:"namespace"`
	LmsUserID   uuid.UUID   `json:"lms_user_id"`
	LmsRoleName LmsRoleType `json:"lms_role_name"`
}

func (q *Queries) IsUserInRole(ctx context.Context, arg IsUserInRoleParams) (bool, error) {
	row := q.db.QueryRow(ctx, isUserInRole, arg.Namespace, arg.LmsUserID, arg.LmsRoleName)
	var in_role bool
	err := row.Scan(&in_role)
	return in_role, err
}

const listEnrollmentsByAdminFilters = `-- name: ListEnrollmentsByAdminFilters :many
SELECT enrollment_id, enrollment_date, progress, status, due_date, created_at, student_id, student_name, student_email, course_id, course_title, course_category, owned_by, instructor_id, category_id, category_name, namespace, tenant_id FROM enrollment_details
WHERE namespace = $1 
    AND ($2::uuid = '00000000-0000-0000-0000-000000000000' OR course_id = $2) 
    AND ($3::uuid = '00000000-0000-0000-0000-000000000000' OR category_id = $3)
    AND ($4::text = '' OR student_email = $4)
`

type ListEnrollmentsByAdminFiltersParams struct {
	Namespace string    `json:"namespace"`
	Column2   uuid.UUID `json:"column_2"`
	Column3   uuid.UUID `json:"column_3"`
	Column4   string    `json:"column_4"`
}

func (q *Queries) ListEnrollmentsByAdminFilters(ctx context.Context, arg ListEnrollmentsByAdminFiltersParams) ([]EnrollmentDetails, error) {
	rows, err := q.db.Query(ctx, listEnrollmentsByAdminFilters,
		arg.Namespace,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EnrollmentDetails{}
	for rows.Next() {
		var i EnrollmentDetails
		if err := rows.Scan(
			&i.EnrollmentID,
			&i.EnrollmentDate,
			&i.Progress,
			&i.Status,
			&i.DueDate,
			&i.CreatedAt,
			&i.StudentID,
			&i.StudentName,
			&i.StudentEmail,
			&i.CourseID,
			&i.CourseTitle,
			&i.CourseCategory,
			&i.OwnedBy,
			&i.InstructorID,
			&i.CategoryID,
			&i.CategoryName,
			&i.Namespace,
			&i.TenantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnrollmentsByInstructorFilters = `-- name: ListEnrollmentsByInstructorFilters :many
SELECT enrollment_id, enrollment_date, progress, status, due_date, created_at, student_id, student_name, student_email, course_id, course_title, course_category, owned_by, instructor_id, category_id, category_name, namespace, tenant_id FROM enrollment_details
WHERE namespace = $1 
    AND instructor_id = $2 
    AND ($3::uuid = '00000000-0000-0000-0000-000000000000' OR course_id = $3) 
    AND ($4::uuid = '00000000-0000-0000-0000-000000000000' OR category_id = $4)
    AND ($5::text = '' OR student_email = $5)
`

type ListEnrollmentsByInstructorFiltersParams struct {
	Namespace    string    `json:"namespace"`
	InstructorID uuid.UUID `json:"instructor_id"`
	Column3      uuid.UUID `json:"column_3"`
	Column4      uuid.UUID `json:"column_4"`
	Column5      string    `json:"column_5"`
}

func (q *Queries) ListEnrollmentsByInstructorFilters(ctx context.Context, arg ListEnrollmentsByInstructorFiltersParams) ([]EnrollmentDetails, error) {
	rows, err := q.db.Query(ctx, listEnrollmentsByInstructorFilters,
		arg.Namespace,
		arg.InstructorID,
		arg.Column3,
		arg.Column4,
		arg.Column5,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EnrollmentDetails{}
	for rows.Next() {
		var i EnrollmentDetails
		if err := rows.Scan(
			&i.EnrollmentID,
			&i.EnrollmentDate,
			&i.Progress,
			&i.Status,
			&i.DueDate,
			&i.CreatedAt,
			&i.StudentID,
			&i.StudentName,
			&i.StudentEmail,
			&i.CourseID,
			&i.CourseTitle,
			&i.CourseCategory,
			&i.OwnedBy,
			&i.InstructorID,
			&i.CategoryID,
			&i.CategoryName,
			&i.Namespace,
			&i.TenantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEnrollmentProgress = `-- name: UpdateEnrollmentProgress :one
UPDATE Enrollment
SET progress    = COALESCE($2, progress),
    updated_at  = CURRENT_TIMESTAMP
WHERE enrollment_id = $1
RETURNING enrollment_id, student_id, course_id, enrollment_date, progress, status, due_date, created_at, updated_at
`

type UpdateEnrollmentProgressParams struct {
	EnrollmentID uuid.UUID      `json:"enrollment_id"`
	Progress     pgtype.Numeric `json:"progress"`
}

func (q *Queries) UpdateEnrollmentProgress(ctx context.Context, arg UpdateEnrollmentProgressParams) (Enrollment, error) {
	row := q.db.QueryRow(ctx, updateEnrollmentProgress, arg.EnrollmentID, arg.Progress)
	var i Enrollment
	err := row.Scan(
		&i.EnrollmentID,
		&i.StudentID,
		&i.CourseID,
		&i.EnrollmentDate,
		&i.Progress,
		&i.Status,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEnrollmentStatus = `-- name: UpdateEnrollmentStatus :one
UPDATE Enrollment
SET status      = COALESCE($2, status),
    updated_at  = CURRENT_TIMESTAMP
WHERE enrollment_id = $1
RETURNING enrollment_id, student_id, course_id, enrollment_date, progress, status, due_date, created_at, updated_at
`

type UpdateEnrollmentStatusParams struct {
	EnrollmentID uuid.UUID      `json:"enrollment_id"`
	Status       EnrollmentType `json:"status"`
}

func (q *Queries) UpdateEnrollmentStatus(ctx context.Context, arg UpdateEnrollmentStatusParams) (Enrollment, error) {
	row := q.db.QueryRow(ctx, updateEnrollmentStatus, arg.EnrollmentID, arg.Status)
	var i Enrollment
	err := row.Scan(
		&i.EnrollmentID,
		&i.StudentID,
		&i.CourseID,
		&i.EnrollmentDate,
		&i.Progress,
		&i.Status,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
