// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: module.sql

package repo

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createModule = `-- name: CreateModule :one
INSERT INTO Module (module_name,
                    course_id,
                    description,
                    updated_at)
VALUES ($1, $2, $3, CURRENT_TIMESTAMP) RETURNING module_id, module_name, course_id, description, created_at, updated_at
`

type CreateModuleParams struct {
	ModuleName  string      `json:"module_name"`
	CourseID    uuid.UUID   `json:"course_id"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateModule(ctx context.Context, arg CreateModuleParams) (Module, error) {
	row := q.db.QueryRow(ctx, createModule, arg.ModuleName, arg.CourseID, arg.Description)
	var i Module
	err := row.Scan(
		&i.ModuleID,
		&i.ModuleName,
		&i.CourseID,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAssociatedLessons = `-- name: DeleteAssociatedLessons :exec
DELETE
FROM Lesson
WHERE module_id = $1
`

func (q *Queries) DeleteAssociatedLessons(ctx context.Context, moduleID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAssociatedLessons, moduleID)
	return err
}

const deleteAssociatedQuizzes = `-- name: DeleteAssociatedQuizzes :exec
DELETE
FROM Quiz
WHERE module_id = $1
`

func (q *Queries) DeleteAssociatedQuizzes(ctx context.Context, moduleID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAssociatedQuizzes, moduleID)
	return err
}

const deleteModule = `-- name: DeleteModule :exec
DELETE
FROM Module
WHERE module_id = $1
`

func (q *Queries) DeleteModule(ctx context.Context, moduleID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteModule, moduleID)
	return err
}

const deleteModules = `-- name: DeleteModules :exec
DELETE
FROM Module
WHERE module_id = ANY ($1::uuid[])
`

func (q *Queries) DeleteModules(ctx context.Context, dollar_1 []uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteModules, dollar_1)
	return err
}

const getModuleByIDWithTenant = `-- name: GetModuleByIDWithTenant :one
SELECT m.module_id, m.module_name, m.course_id, m.description, m.created_at, m.updated_at
FROM Module m
JOIN Course c ON c.course_id = m.course_id
JOIN Tenants t ON c.owned_by = t.tenant_id
WHERE m.module_id = $1 AND t.namespace = $2
`

type GetModuleByIDWithTenantParams struct {
	ModuleID  uuid.UUID `json:"module_id"`
	Namespace string    `json:"namespace"`
}

func (q *Queries) GetModuleByIDWithTenant(ctx context.Context, arg GetModuleByIDWithTenantParams) (Module, error) {
	row := q.db.QueryRow(ctx, getModuleByIDWithTenant, arg.ModuleID, arg.Namespace)
	var i Module
	err := row.Scan(
		&i.ModuleID,
		&i.ModuleName,
		&i.CourseID,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const isCourseOwnedByTenant = `-- name: IsCourseOwnedByTenant :one
SELECT EXISTS (
    SELECT 1 
    FROM Course c
    JOIN Tenants t ON c.owned_by = t.tenant_id
    WHERE c.course_id = $1 AND t.namespace = $2
) AS is_owned
`

type IsCourseOwnedByTenantParams struct {
	CourseID  uuid.UUID `json:"course_id"`
	Namespace string    `json:"namespace"`
}

func (q *Queries) IsCourseOwnedByTenant(ctx context.Context, arg IsCourseOwnedByTenantParams) (bool, error) {
	row := q.db.QueryRow(ctx, isCourseOwnedByTenant, arg.CourseID, arg.Namespace)
	var is_owned bool
	err := row.Scan(&is_owned)
	return is_owned, err
}

const isModuleOwnedByTenant = `-- name: IsModuleOwnedByTenant :one
SELECT EXISTS (
    SELECT 1
    FROM Module m
    JOIN Course c ON c.course_id = m.course_id
    JOIN Tenants t ON c.owned_by = t.tenant_id
    WHERE m.module_id = $1 AND t.namespace = $2
) as is_owned
`

type IsModuleOwnedByTenantParams struct {
	ModuleID  uuid.UUID `json:"module_id"`
	Namespace string    `json:"namespace"`
}

func (q *Queries) IsModuleOwnedByTenant(ctx context.Context, arg IsModuleOwnedByTenantParams) (bool, error) {
	row := q.db.QueryRow(ctx, isModuleOwnedByTenant, arg.ModuleID, arg.Namespace)
	var is_owned bool
	err := row.Scan(&is_owned)
	return is_owned, err
}

const listModulesWithTenant = `-- name: ListModulesWithTenant :many
SELECT m.module_id, m.module_name, m.course_id, m.description, m.created_at, m.updated_at
FROM Module m
JOIN Course c ON c.course_id = m.course_id
JOIN Tenants t ON c.owned_by = t.tenant_id
WHERE t.namespace = $1
ORDER BY m.created_at DESC
`

func (q *Queries) ListModulesWithTenant(ctx context.Context, namespace string) ([]Module, error) {
	rows, err := q.db.Query(ctx, listModulesWithTenant, namespace)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Module{}
	for rows.Next() {
		var i Module
		if err := rows.Scan(
			&i.ModuleID,
			&i.ModuleName,
			&i.CourseID,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moduleHasAssociations = `-- name: ModuleHasAssociations :one
SELECT (
           (SELECT COUNT(*) FROM Quiz q WHERE q.module_id = $1) > 0
               OR
           (SELECT COUNT(*) FROM Lesson l WHERE l.module_id = $1) > 0
           ) AS exists
`

func (q *Queries) ModuleHasAssociations(ctx context.Context, moduleID uuid.UUID) (pgtype.Bool, error) {
	row := q.db.QueryRow(ctx, moduleHasAssociations, moduleID)
	var exists pgtype.Bool
	err := row.Scan(&exists)
	return exists, err
}

const updateModuleByID = `-- name: UpdateModuleByID :one
UPDATE Module
SET module_name = COALESCE($2, module_name),
    course_id   = COALESCE($3, course_id),
    description = COALESCE($4, description),
    updated_at  = CURRENT_TIMESTAMP
WHERE module_id = $1 RETURNING module_id, module_name, course_id, description, created_at, updated_at
`

type UpdateModuleByIDParams struct {
	ModuleID    uuid.UUID   `json:"module_id"`
	ModuleName  string      `json:"module_name"`
	CourseID    uuid.UUID   `json:"course_id"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) UpdateModuleByID(ctx context.Context, arg UpdateModuleByIDParams) (Module, error) {
	row := q.db.QueryRow(ctx, updateModuleByID,
		arg.ModuleID,
		arg.ModuleName,
		arg.CourseID,
		arg.Description,
	)
	var i Module
	err := row.Scan(
		&i.ModuleID,
		&i.ModuleName,
		&i.CourseID,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
