// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tables.sql

package repo

import (
	"context"
)

const getAllTables = `-- name: GetAllTables :many
SELECT table_name
FROM information_schema.tables
WHERE table_schema = $1
  AND table_type = 'BASE TABLE'
ORDER BY table_name
`

func (q *Queries) GetAllTables(ctx context.Context, tableSchema interface{}) ([]interface{}, error) {
	rows, err := q.db.Query(ctx, getAllTables, tableSchema)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []interface{}{}
	for rows.Next() {
		var table_name interface{}
		if err := rows.Scan(&table_name); err != nil {
			return nil, err
		}
		items = append(items, table_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
