// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: authentication/authentication.proto

package authentication

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Is equal to the LMS USER
type SystemUser struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username         string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email            string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber      string                 `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Address          string                 `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	RegistrationDate *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=registration_date,json=registrationDate,proto3" json:"registration_date,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SystemUser) Reset() {
	*x = SystemUser{}
	mi := &file_authentication_authentication_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemUser) ProtoMessage() {}

func (x *SystemUser) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_authentication_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemUser.ProtoReflect.Descriptor instead.
func (*SystemUser) Descriptor() ([]byte, []int) {
	return file_authentication_authentication_proto_rawDescGZIP(), []int{0}
}

func (x *SystemUser) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SystemUser) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SystemUser) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SystemUser) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *SystemUser) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *SystemUser) GetRegistrationDate() *timestamppb.Timestamp {
	if x != nil {
		return x.RegistrationDate
	}
	return nil
}

func (x *SystemUser) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SystemUser) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_authentication_authentication_proto protoreflect.FileDescriptor

const file_authentication_authentication_proto_rawDesc = "" +
	"\n" +
	"#authentication/authentication.proto\x12\x12lms.authentication\x1a\x1fgoogle/protobuf/timestamp.proto\"\xca\x02\n" +
	"\n" +
	"SystemUser\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12!\n" +
	"\fphone_number\x18\x04 \x01(\tR\vphoneNumber\x12\x18\n" +
	"\aaddress\x18\x05 \x01(\tR\aaddress\x12G\n" +
	"\x11registration_date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x10registrationDate\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtBDZBgithub.com/multi-tenant-cms-golang/lms-sys/protogen/authenticationb\x06proto3"

var (
	file_authentication_authentication_proto_rawDescOnce sync.Once
	file_authentication_authentication_proto_rawDescData []byte
)

func file_authentication_authentication_proto_rawDescGZIP() []byte {
	file_authentication_authentication_proto_rawDescOnce.Do(func() {
		file_authentication_authentication_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_authentication_authentication_proto_rawDesc), len(file_authentication_authentication_proto_rawDesc)))
	})
	return file_authentication_authentication_proto_rawDescData
}

var file_authentication_authentication_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_authentication_authentication_proto_goTypes = []any{
	(*SystemUser)(nil),            // 0: lms.authentication.SystemUser
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_authentication_authentication_proto_depIdxs = []int32{
	1, // 0: lms.authentication.SystemUser.registration_date:type_name -> google.protobuf.Timestamp
	1, // 1: lms.authentication.SystemUser.created_at:type_name -> google.protobuf.Timestamp
	1, // 2: lms.authentication.SystemUser.updated_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_authentication_authentication_proto_init() }
func file_authentication_authentication_proto_init() {
	if File_authentication_authentication_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_authentication_authentication_proto_rawDesc), len(file_authentication_authentication_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_authentication_authentication_proto_goTypes,
		DependencyIndexes: file_authentication_authentication_proto_depIdxs,
		MessageInfos:      file_authentication_authentication_proto_msgTypes,
	}.Build()
	File_authentication_authentication_proto = out.File
	file_authentication_authentication_proto_goTypes = nil
	file_authentication_authentication_proto_depIdxs = nil
}
