// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: authentication/rpc_email_verify.proto

package authentication

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmailVerifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Organisation  string                 `protobuf:"bytes,1,opt,name=organisation,proto3" json:"organisation,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailVerifyRequest) Reset() {
	*x = EmailVerifyRequest{}
	mi := &file_authentication_rpc_email_verify_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailVerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailVerifyRequest) ProtoMessage() {}

func (x *EmailVerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_rpc_email_verify_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailVerifyRequest.ProtoReflect.Descriptor instead.
func (*EmailVerifyRequest) Descriptor() ([]byte, []int) {
	return file_authentication_rpc_email_verify_proto_rawDescGZIP(), []int{0}
}

func (x *EmailVerifyRequest) GetOrganisation() string {
	if x != nil {
		return x.Organisation
	}
	return ""
}

func (x *EmailVerifyRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *EmailVerifyRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type EmailVerifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailVerifyResponse) Reset() {
	*x = EmailVerifyResponse{}
	mi := &file_authentication_rpc_email_verify_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailVerifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailVerifyResponse) ProtoMessage() {}

func (x *EmailVerifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_rpc_email_verify_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailVerifyResponse.ProtoReflect.Descriptor instead.
func (*EmailVerifyResponse) Descriptor() ([]byte, []int) {
	return file_authentication_rpc_email_verify_proto_rawDescGZIP(), []int{1}
}

func (x *EmailVerifyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_authentication_rpc_email_verify_proto protoreflect.FileDescriptor

const file_authentication_rpc_email_verify_proto_rawDesc = "" +
	"\n" +
	"%authentication/rpc_email_verify.proto\x12\x12lms.authentication\x1a\x1fgoogle/protobuf/timestamp.proto\"d\n" +
	"\x12EmailVerifyRequest\x12\"\n" +
	"\forganisation\x18\x01 \x01(\tR\forganisation\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\"/\n" +
	"\x13EmailVerifyResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessageBDZBgithub.com/multi-tenant-cms-golang/lms-sys/protogen/authenticationb\x06proto3"

var (
	file_authentication_rpc_email_verify_proto_rawDescOnce sync.Once
	file_authentication_rpc_email_verify_proto_rawDescData []byte
)

func file_authentication_rpc_email_verify_proto_rawDescGZIP() []byte {
	file_authentication_rpc_email_verify_proto_rawDescOnce.Do(func() {
		file_authentication_rpc_email_verify_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_authentication_rpc_email_verify_proto_rawDesc), len(file_authentication_rpc_email_verify_proto_rawDesc)))
	})
	return file_authentication_rpc_email_verify_proto_rawDescData
}

var file_authentication_rpc_email_verify_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_authentication_rpc_email_verify_proto_goTypes = []any{
	(*EmailVerifyRequest)(nil),  // 0: lms.authentication.EmailVerifyRequest
	(*EmailVerifyResponse)(nil), // 1: lms.authentication.EmailVerifyResponse
}
var file_authentication_rpc_email_verify_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_authentication_rpc_email_verify_proto_init() }
func file_authentication_rpc_email_verify_proto_init() {
	if File_authentication_rpc_email_verify_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_authentication_rpc_email_verify_proto_rawDesc), len(file_authentication_rpc_email_verify_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_authentication_rpc_email_verify_proto_goTypes,
		DependencyIndexes: file_authentication_rpc_email_verify_proto_depIdxs,
		MessageInfos:      file_authentication_rpc_email_verify_proto_msgTypes,
	}.Build()
	File_authentication_rpc_email_verify_proto = out.File
	file_authentication_rpc_email_verify_proto_goTypes = nil
	file_authentication_rpc_email_verify_proto_depIdxs = nil
}
