// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: tenants/rpc_tenants_create.proto

package tenants

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	CmsOwnerId    string                 `protobuf:"bytes,2,opt,name=cms_owner_id,json=cmsOwnerId,proto3" json:"cms_owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTenantRequest) Reset() {
	*x = CreateTenantRequest{}
	mi := &file_tenants_rpc_tenants_create_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTenantRequest) ProtoMessage() {}

func (x *CreateTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenants_rpc_tenants_create_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTenantRequest.ProtoReflect.Descriptor instead.
func (*CreateTenantRequest) Descriptor() ([]byte, []int) {
	return file_tenants_rpc_tenants_create_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTenantRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *CreateTenantRequest) GetCmsOwnerId() string {
	if x != nil {
		return x.CmsOwnerId
	}
	return ""
}

type CreateTenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatedTenant *Tenants               `protobuf:"bytes,1,opt,name=created_tenant,json=createdTenant,proto3" json:"created_tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTenantResponse) Reset() {
	*x = CreateTenantResponse{}
	mi := &file_tenants_rpc_tenants_create_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTenantResponse) ProtoMessage() {}

func (x *CreateTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenants_rpc_tenants_create_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTenantResponse.ProtoReflect.Descriptor instead.
func (*CreateTenantResponse) Descriptor() ([]byte, []int) {
	return file_tenants_rpc_tenants_create_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTenantResponse) GetCreatedTenant() *Tenants {
	if x != nil {
		return x.CreatedTenant
	}
	return nil
}

var File_tenants_rpc_tenants_create_proto protoreflect.FileDescriptor

const file_tenants_rpc_tenants_create_proto_rawDesc = "" +
	"\n" +
	" tenants/rpc_tenants_create.proto\x12\vlms.tenants\x1a\x15tenants/tenants.proto\"U\n" +
	"\x13CreateTenantRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12 \n" +
	"\fcms_owner_id\x18\x02 \x01(\tR\n" +
	"cmsOwnerId\"S\n" +
	"\x14CreateTenantResponse\x12;\n" +
	"\x0ecreated_tenant\x18\x01 \x01(\v2\x14.lms.tenants.TenantsR\rcreatedTenantB>Z<github.com/multi-tenants-cms-golang/lms-sys/protogen/tenantsb\x06proto3"

var (
	file_tenants_rpc_tenants_create_proto_rawDescOnce sync.Once
	file_tenants_rpc_tenants_create_proto_rawDescData []byte
)

func file_tenants_rpc_tenants_create_proto_rawDescGZIP() []byte {
	file_tenants_rpc_tenants_create_proto_rawDescOnce.Do(func() {
		file_tenants_rpc_tenants_create_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tenants_rpc_tenants_create_proto_rawDesc), len(file_tenants_rpc_tenants_create_proto_rawDesc)))
	})
	return file_tenants_rpc_tenants_create_proto_rawDescData
}

var file_tenants_rpc_tenants_create_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tenants_rpc_tenants_create_proto_goTypes = []any{
	(*CreateTenantRequest)(nil),  // 0: lms.tenants.CreateTenantRequest
	(*CreateTenantResponse)(nil), // 1: lms.tenants.CreateTenantResponse
	(*Tenants)(nil),              // 2: lms.tenants.Tenants
}
var file_tenants_rpc_tenants_create_proto_depIdxs = []int32{
	2, // 0: lms.tenants.CreateTenantResponse.created_tenant:type_name -> lms.tenants.Tenants
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_tenants_rpc_tenants_create_proto_init() }
func file_tenants_rpc_tenants_create_proto_init() {
	if File_tenants_rpc_tenants_create_proto != nil {
		return
	}
	file_tenants_tenants_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tenants_rpc_tenants_create_proto_rawDesc), len(file_tenants_rpc_tenants_create_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tenants_rpc_tenants_create_proto_goTypes,
		DependencyIndexes: file_tenants_rpc_tenants_create_proto_depIdxs,
		MessageInfos:      file_tenants_rpc_tenants_create_proto_msgTypes,
	}.Build()
	File_tenants_rpc_tenants_create_proto = out.File
	file_tenants_rpc_tenants_create_proto_goTypes = nil
	file_tenants_rpc_tenants_create_proto_depIdxs = nil
}
