// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: module/rpc_create_module.proto

package module

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateModuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModuleName    string                 `protobuf:"bytes,1,opt,name=module_name,json=moduleName,proto3" json:"module_name,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateModuleRequest) Reset() {
	*x = CreateModuleRequest{}
	mi := &file_module_rpc_create_module_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateModuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateModuleRequest) ProtoMessage() {}

func (x *CreateModuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_module_rpc_create_module_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateModuleRequest.ProtoReflect.Descriptor instead.
func (*CreateModuleRequest) Descriptor() ([]byte, []int) {
	return file_module_rpc_create_module_proto_rawDescGZIP(), []int{0}
}

func (x *CreateModuleRequest) GetModuleName() string {
	if x != nil {
		return x.ModuleName
	}
	return ""
}

func (x *CreateModuleRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *CreateModuleRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateModuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        *Module                `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateModuleResponse) Reset() {
	*x = CreateModuleResponse{}
	mi := &file_module_rpc_create_module_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateModuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateModuleResponse) ProtoMessage() {}

func (x *CreateModuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_module_rpc_create_module_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateModuleResponse.ProtoReflect.Descriptor instead.
func (*CreateModuleResponse) Descriptor() ([]byte, []int) {
	return file_module_rpc_create_module_proto_rawDescGZIP(), []int{1}
}

func (x *CreateModuleResponse) GetModule() *Module {
	if x != nil {
		return x.Module
	}
	return nil
}

var File_module_rpc_create_module_proto protoreflect.FileDescriptor

const file_module_rpc_create_module_proto_rawDesc = "" +
	"\n" +
	"\x1emodule/rpc_create_module.proto\x12\vlms.modules\x1a\x13module/module.proto\"u\n" +
	"\x13CreateModuleRequest\x12\x1f\n" +
	"\vmodule_name\x18\x01 \x01(\tR\n" +
	"moduleName\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"C\n" +
	"\x14CreateModuleResponse\x12+\n" +
	"\x06module\x18\x01 \x01(\v2\x13.lms.modules.ModuleR\x06moduleB<Z:github.com/multi-tenant-cms-doc-golang/lms-sys/protogen/moduleb\x06proto3"

var (
	file_module_rpc_create_module_proto_rawDescOnce sync.Once
	file_module_rpc_create_module_proto_rawDescData []byte
)

func file_module_rpc_create_module_proto_rawDescGZIP() []byte {
	file_module_rpc_create_module_proto_rawDescOnce.Do(func() {
		file_module_rpc_create_module_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_module_rpc_create_module_proto_rawDesc), len(file_module_rpc_create_module_proto_rawDesc)))
	})
	return file_module_rpc_create_module_proto_rawDescData
}

var file_module_rpc_create_module_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_module_rpc_create_module_proto_goTypes = []any{
	(*CreateModuleRequest)(nil),  // 0: lms.modules.CreateModuleRequest
	(*CreateModuleResponse)(nil), // 1: lms.modules.CreateModuleResponse
	(*Module)(nil),               // 2: lms.modules.Module
}
var file_module_rpc_create_module_proto_depIdxs = []int32{
	2, // 0: lms.modules.CreateModuleResponse.module:type_name -> lms.modules.Module
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_module_rpc_create_module_proto_init() }
func file_module_rpc_create_module_proto_init() {
	if File_module_rpc_create_module_proto != nil {
		return
	}
	file_module_module_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_module_rpc_create_module_proto_rawDesc), len(file_module_rpc_create_module_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_module_rpc_create_module_proto_goTypes,
		DependencyIndexes: file_module_rpc_create_module_proto_depIdxs,
		MessageInfos:      file_module_rpc_create_module_proto_msgTypes,
	}.Build()
	File_module_rpc_create_module_proto = out.File
	file_module_rpc_create_module_proto_goTypes = nil
	file_module_rpc_create_module_proto_depIdxs = nil
}
