// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: users/rpc_user_create.proto

package users

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateLMSUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LmsEmail      string                 `protobuf:"bytes,1,opt,name=lms_email,json=lmsEmail,proto3" json:"lms_email,omitempty"`
	LmsRoleId     string                 `protobuf:"bytes,2,opt,name=lms_role_id,json=lmsRoleId,proto3" json:"lms_role_id,omitempty"`
	TenantsId     string                 `protobuf:"bytes,3,opt,name=tenants_id,json=tenantsId,proto3" json:"tenants_id,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,5,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLMSUserRequest) Reset() {
	*x = CreateLMSUserRequest{}
	mi := &file_users_rpc_user_create_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLMSUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLMSUserRequest) ProtoMessage() {}

func (x *CreateLMSUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_rpc_user_create_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLMSUserRequest.ProtoReflect.Descriptor instead.
func (*CreateLMSUserRequest) Descriptor() ([]byte, []int) {
	return file_users_rpc_user_create_proto_rawDescGZIP(), []int{0}
}

func (x *CreateLMSUserRequest) GetLmsEmail() string {
	if x != nil {
		return x.LmsEmail
	}
	return ""
}

func (x *CreateLMSUserRequest) GetLmsRoleId() string {
	if x != nil {
		return x.LmsRoleId
	}
	return ""
}

func (x *CreateLMSUserRequest) GetTenantsId() string {
	if x != nil {
		return x.TenantsId
	}
	return ""
}

func (x *CreateLMSUserRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreateLMSUserRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

type CreateLMSUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserResponse  *Users                 `protobuf:"bytes,1,opt,name=user_response,json=userResponse,proto3" json:"user_response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLMSUserResponse) Reset() {
	*x = CreateLMSUserResponse{}
	mi := &file_users_rpc_user_create_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLMSUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLMSUserResponse) ProtoMessage() {}

func (x *CreateLMSUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_rpc_user_create_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLMSUserResponse.ProtoReflect.Descriptor instead.
func (*CreateLMSUserResponse) Descriptor() ([]byte, []int) {
	return file_users_rpc_user_create_proto_rawDescGZIP(), []int{1}
}

func (x *CreateLMSUserResponse) GetUserResponse() *Users {
	if x != nil {
		return x.UserResponse
	}
	return nil
}

var File_users_rpc_user_create_proto protoreflect.FileDescriptor

const file_users_rpc_user_create_proto_rawDesc = "" +
	"\n" +
	"\x1busers/rpc_user_create.proto\x12\tlms.users\x1a\x11users/users.proto\"\xaf\x01\n" +
	"\x14CreateLMSUserRequest\x12\x1b\n" +
	"\tlms_email\x18\x01 \x01(\tR\blmsEmail\x12\x1e\n" +
	"\vlms_role_id\x18\x02 \x01(\tR\tlmsRoleId\x12\x1d\n" +
	"\n" +
	"tenants_id\x18\x03 \x01(\tR\ttenantsId\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12!\n" +
	"\fphone_number\x18\x05 \x01(\tR\vphoneNumber\"N\n" +
	"\x15CreateLMSUserResponse\x125\n" +
	"\ruser_response\x18\x01 \x01(\v2\x10.lms.users.UsersR\fuserResponseB;Z9github.com/multi-tenant-cms-golang/lms-sys/protogen/usersb\x06proto3"

var (
	file_users_rpc_user_create_proto_rawDescOnce sync.Once
	file_users_rpc_user_create_proto_rawDescData []byte
)

func file_users_rpc_user_create_proto_rawDescGZIP() []byte {
	file_users_rpc_user_create_proto_rawDescOnce.Do(func() {
		file_users_rpc_user_create_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_users_rpc_user_create_proto_rawDesc), len(file_users_rpc_user_create_proto_rawDesc)))
	})
	return file_users_rpc_user_create_proto_rawDescData
}

var file_users_rpc_user_create_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_users_rpc_user_create_proto_goTypes = []any{
	(*CreateLMSUserRequest)(nil),  // 0: lms.users.CreateLMSUserRequest
	(*CreateLMSUserResponse)(nil), // 1: lms.users.CreateLMSUserResponse
	(*Users)(nil),                 // 2: lms.users.Users
}
var file_users_rpc_user_create_proto_depIdxs = []int32{
	2, // 0: lms.users.CreateLMSUserResponse.user_response:type_name -> lms.users.Users
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_users_rpc_user_create_proto_init() }
func file_users_rpc_user_create_proto_init() {
	if File_users_rpc_user_create_proto != nil {
		return
	}
	file_users_users_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_users_rpc_user_create_proto_rawDesc), len(file_users_rpc_user_create_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_users_rpc_user_create_proto_goTypes,
		DependencyIndexes: file_users_rpc_user_create_proto_depIdxs,
		MessageInfos:      file_users_rpc_user_create_proto_msgTypes,
	}.Build()
	File_users_rpc_user_create_proto = out.File
	file_users_rpc_user_create_proto_goTypes = nil
	file_users_rpc_user_create_proto_depIdxs = nil
}
