// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: users/users.proto

package users

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Users struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	LmsEmail         string                 `protobuf:"bytes,2,opt,name=lms_email,json=lmsEmail,proto3" json:"lms_email,omitempty"`
	LmsRoleId        string                 `protobuf:"bytes,3,opt,name=lms_role_id,json=lmsRoleId,proto3" json:"lms_role_id,omitempty"`
	TenantsId        string                 `protobuf:"bytes,4,opt,name=tenants_id,json=tenantsId,proto3" json:"tenants_id,omitempty"`
	Address          string                 `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	PhoneNumber      string                 `protobuf:"bytes,6,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	RegistrationDate *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=registration_date,json=registrationDate,proto3" json:"registration_date,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Users) Reset() {
	*x = Users{}
	mi := &file_users_users_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Users) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Users) ProtoMessage() {}

func (x *Users) ProtoReflect() protoreflect.Message {
	mi := &file_users_users_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Users.ProtoReflect.Descriptor instead.
func (*Users) Descriptor() ([]byte, []int) {
	return file_users_users_proto_rawDescGZIP(), []int{0}
}

func (x *Users) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Users) GetLmsEmail() string {
	if x != nil {
		return x.LmsEmail
	}
	return ""
}

func (x *Users) GetLmsRoleId() string {
	if x != nil {
		return x.LmsRoleId
	}
	return ""
}

func (x *Users) GetTenantsId() string {
	if x != nil {
		return x.TenantsId
	}
	return ""
}

func (x *Users) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Users) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *Users) GetRegistrationDate() *timestamppb.Timestamp {
	if x != nil {
		return x.RegistrationDate
	}
	return nil
}

func (x *Users) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Users) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_users_users_proto protoreflect.FileDescriptor

const file_users_users_proto_rawDesc = "" +
	"\n" +
	"\x11users/users.proto\x12\tlms.users\x1a\x1fgoogle/protobuf/timestamp.proto\"\xef\x02\n" +
	"\x05Users\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tlms_email\x18\x02 \x01(\tR\blmsEmail\x12\x1e\n" +
	"\vlms_role_id\x18\x03 \x01(\tR\tlmsRoleId\x12\x1d\n" +
	"\n" +
	"tenants_id\x18\x04 \x01(\tR\ttenantsId\x12\x18\n" +
	"\aaddress\x18\x05 \x01(\tR\aaddress\x12!\n" +
	"\fphone_number\x18\x06 \x01(\tR\vphoneNumber\x12G\n" +
	"\x11registration_date\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x10registrationDate\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB;Z9github.com/multi-tenant-cms-golang/lms-sys/protogen/usersb\x06proto3"

var (
	file_users_users_proto_rawDescOnce sync.Once
	file_users_users_proto_rawDescData []byte
)

func file_users_users_proto_rawDescGZIP() []byte {
	file_users_users_proto_rawDescOnce.Do(func() {
		file_users_users_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_users_users_proto_rawDesc), len(file_users_users_proto_rawDesc)))
	})
	return file_users_users_proto_rawDescData
}

var file_users_users_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_users_users_proto_goTypes = []any{
	(*Users)(nil),                 // 0: lms.users.Users
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_users_users_proto_depIdxs = []int32{
	1, // 0: lms.users.Users.registration_date:type_name -> google.protobuf.Timestamp
	1, // 1: lms.users.Users.created_at:type_name -> google.protobuf.Timestamp
	1, // 2: lms.users.Users.updated_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_users_users_proto_init() }
func file_users_users_proto_init() {
	if File_users_users_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_users_users_proto_rawDesc), len(file_users_users_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_users_users_proto_goTypes,
		DependencyIndexes: file_users_users_proto_depIdxs,
		MessageInfos:      file_users_users_proto_msgTypes,
	}.Build()
	File_users_users_proto = out.File
	file_users_users_proto_goTypes = nil
	file_users_users_proto_depIdxs = nil
}
