// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.21.12
// source: quiz/rpc_quiz_create.proto

package quiz

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateQuizRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ModuleId string           `protobuf:"bytes,1,opt,name=moduleId,proto3" json:"moduleId,omitempty"`
	Quiz     []*QuestionInput `protobuf:"bytes,2,rep,name=quiz,proto3" json:"quiz,omitempty"`
}

func (x *CreateQuizRequest) Reset() {
	*x = CreateQuizRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quiz_rpc_quiz_create_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateQuizRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQuizRequest) ProtoMessage() {}

func (x *CreateQuizRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_rpc_quiz_create_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQuizRequest.ProtoReflect.Descriptor instead.
func (*CreateQuizRequest) Descriptor() ([]byte, []int) {
	return file_quiz_rpc_quiz_create_proto_rawDescGZIP(), []int{0}
}

func (x *CreateQuizRequest) GetModuleId() string {
	if x != nil {
		return x.ModuleId
	}
	return ""
}

func (x *CreateQuizRequest) GetQuiz() []*QuestionInput {
	if x != nil {
		return x.Quiz
	}
	return nil
}

var File_quiz_rpc_quiz_create_proto protoreflect.FileDescriptor

var file_quiz_rpc_quiz_create_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x71, 0x75, 0x69, 0x7a, 0x2f, 0x72, 0x70, 0x63, 0x5f, 0x71, 0x75, 0x69, 0x7a, 0x5f,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x6c, 0x6d,
	0x73, 0x2e, 0x71, 0x75, 0x69, 0x7a, 0x1a, 0x0f, 0x71, 0x75, 0x69, 0x7a, 0x2f, 0x71, 0x75, 0x69,
	0x7a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5c, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x51, 0x75, 0x69, 0x7a, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x2b, 0x0a, 0x04, 0x71, 0x75, 0x69, 0x7a,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6c, 0x6d, 0x73, 0x2e, 0x71, 0x75, 0x69,
	0x7a, 0x2e, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x52,
	0x04, 0x71, 0x75, 0x69, 0x7a, 0x42, 0x3a, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x2d, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74,
	0x2d, 0x63, 0x6d, 0x73, 0x2d, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2f, 0x6c, 0x6d, 0x73, 0x2d,
	0x73, 0x79, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x67, 0x65, 0x6e, 0x2f, 0x71, 0x75, 0x69,
	0x7a, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_quiz_rpc_quiz_create_proto_rawDescOnce sync.Once
	file_quiz_rpc_quiz_create_proto_rawDescData = file_quiz_rpc_quiz_create_proto_rawDesc
)

func file_quiz_rpc_quiz_create_proto_rawDescGZIP() []byte {
	file_quiz_rpc_quiz_create_proto_rawDescOnce.Do(func() {
		file_quiz_rpc_quiz_create_proto_rawDescData = protoimpl.X.CompressGZIP(file_quiz_rpc_quiz_create_proto_rawDescData)
	})
	return file_quiz_rpc_quiz_create_proto_rawDescData
}

var file_quiz_rpc_quiz_create_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_quiz_rpc_quiz_create_proto_goTypes = []interface{}{
	(*CreateQuizRequest)(nil), // 0: lms.quiz.CreateQuizRequest
	(*QuestionInput)(nil),     // 1: lms.quiz.QuestionInput
}
var file_quiz_rpc_quiz_create_proto_depIdxs = []int32{
	1, // 0: lms.quiz.CreateQuizRequest.quiz:type_name -> lms.quiz.QuestionInput
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_quiz_rpc_quiz_create_proto_init() }
func file_quiz_rpc_quiz_create_proto_init() {
	if File_quiz_rpc_quiz_create_proto != nil {
		return
	}
	file_quiz_quiz_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_quiz_rpc_quiz_create_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateQuizRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_quiz_rpc_quiz_create_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_quiz_rpc_quiz_create_proto_goTypes,
		DependencyIndexes: file_quiz_rpc_quiz_create_proto_depIdxs,
		MessageInfos:      file_quiz_rpc_quiz_create_proto_msgTypes,
	}.Build()
	File_quiz_rpc_quiz_create_proto = out.File
	file_quiz_rpc_quiz_create_proto_rawDesc = nil
	file_quiz_rpc_quiz_create_proto_goTypes = nil
	file_quiz_rpc_quiz_create_proto_depIdxs = nil
}
